### ISSUE TITLE
Publish versioning/compatibility strategy or follow semver

### ISSUE THREAD

**Issue by radeksimko** [codecov/codecov-action#100]
👋 

I'm not sure what's your preferred versioning strategy, but it may be worth documenting it, or following [semver](https://semver.org), which seems to be the most common choice for other GitHub Actions.

In that case `v1.X.Y` should be just compatible and therefore `v1` should be pointing to any latest v1 version. Right now `v1` is quite outdated, which causes confusions, e.g. https://github.com/codecov/codecov-action/issues/80

[GitHub Actions docs](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsuses) recommend this major-version-only pattern with the following explanation:

> Using the specific major action version allows you to receive critical fixes and security patches while still maintaining compatibility. It also assures that your workflow should still work.

which I think basically implies that it expects Actions to just follow semver.

**Comment by thomasrockhu** [comment]
Hi @radeksimko, we are choosing to follow with `semver`, but you are right, `v1` is pointing to the wrong version. I have updated the tag, so it should be pointing appropriately.
