### ISSUE TITLE
Upload error still passes

### ISSUE THREAD

**Issue by max-sixty** [codecov/codecov-action#1002]
In [this run](https://github.com/PRQL/prql/actions/runs/5327425077/jobs/9650798492?pr=2877#step:6:46), the action failed to upload, receiving a 502.

Very understandable to get an occasional error. But the action reported success — is that intended?

Thanks!

**Comment by maestromac** [comment]
You'd need to enable this option, or it will fail silently

```
fail_ci_if_error: true # optional (default = false)
```

**Comment by webknjaz** [comment]
#1244
