### ISSUE TITLE
Repository `codecov.yml` not registering.

### ISSUE THREAD

**Issue by connor-ricks** [codecov/codecov-action#1029]
Hello, I started using Codecov in my [repository](https://github.com/connor-ricks/swift-nibbles) this weekend, and for whatever reason, the action is not running with my yaml config.

I have created a `codecov.yml` file in the root of my project, and I have validated it using the following command in terminal.
```
cat codecov.yml | curl --data-binary @- https://codecov.io/validate
```

Here is the [`codecov.yml`](https://github.com/connor-ricks/swift-nibbles/blob/main/codecov.yml)
Here is the [`pull_request_checks.yml`](https://github.com/connor-ricks/swift-nibbles/blob/main/.github/workflows/pull_request_checks.yml) that runs on PRs and utilizes `codecov/codecov-action@v3`

On the Codecov website I am not seeing the yaml populated either.

<img width="1196" alt="Screenshot 2023-07-24 at 10 46 23 AM" src="https://github.com/codecov/codecov-action/assets/13373737/08454925-9b50-481d-9cd2-242aa4e50826">

**Comment by zhiwei-homage** [comment]
hi @connor-ricks 
How did you fix this issue? 
I encountered the same issue now.
Looking forward to your reply, thx a lot.

**Comment by connor-ricks** [comment]
I think I renamed everything to yaml instead of yml.

**Comment by zhiwei-homage** [comment]
> I think I renamed everything to yaml instead of yml.

oh my god, how did you figure out this?
All docs say `yml` not `yaml`.
Let me give it a try, thx a lot 👍
