### ISSUE TITLE
Codecov action takes a long time and fails

### ISSUE THREAD

**Issue by lwasyl** [codecov/codecov-action#104]
![image](https://user-images.githubusercontent.com/3951580/89649107-854da480-d8c0-11ea-83ff-eeacd4d64b18.png)

Even when fetching codecov script fails, I think it should take much less time than 10 minutes to finally stop (or maybe try refetching the script more than once)

**Comment by thefirstofthe300** [comment]
I think this may be related to a server-side CodeCov issue. My pipeline is able to run and upload the coverage status for my test suite for two of the three Python versions in my GHA matrix. The first one seems to happen quickly; the second takes a little longer; the third one errors out with 
```
Run codecov/codecov-action@v1
  with:
    file: ./coverage.xml
    flags: unittests
    env_vars: OS,PYTHON
    fail_ci_if_error: true
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.6.11/x64
##[error]Codecov failed with the following error: connect ETIMEDOUT 35.199.43.247:443
```

The successful test results

```
Run codecov/codecov-action@v1
  with:
    file: ./coverage.xml
    flags: unittests
    env_vars: OS,PYTHON
    fail_ci_if_error: true
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.7.8/x64
bash codecov.sh -f ./coverage.xml -n  -F unittests -Z -e OS,PYTHON

  _____          _
 / ____|        | |
| |     ___   __| | ___  ___ _____   __
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
| |___| (_) | (_| |  __/ (_| (_) \ V /
 \_____\___/ \__,_|\___|\___\___/ \_/
                              Bash-20200728-9fb7d93


==> GitHub Actions detected.
    project root: .
    Yaml found at: codecov.yml
    -> Found 1 reports
==> Detecting git/mercurial file structure
==> Appending build variables
    + OS
    + PYTHON
==> Reading reports
```

**Comment by saroad2** [comment]
I'm having the same problem.

**Comment by kriegfrj** [comment]
I just hit this one now: https://github.com/osgi/osgi-test/pull/174/checks?check_run_id=969430613

I think the timeout could be a lot shorter, as @lwasyl said.

Moreover, even though the upload clearly failed, in the GitHub action report it displays with a green tick. I'm not sure that this is right either.

**Comment by adriangb** [comment]
Also experiencing this.

**Comment by trallnag** [comment]
I have the same issue. @kriegfrj you can let the job fail with `fail_ci_if_error: true`

**Comment by trallnag** [comment]
![image](https://user-images.githubusercontent.com/24834206/90021439-8f511800-dcb1-11ea-9305-04a2ce94f2dd.png)

Same thing happens to me quite often. Wish there was at least a way to lower the time out

**Comment by mathieu-bour** [comment]
I'm also experiencing very long time before failing. Moreover, there is no incident on Codecov's status page: https://status.codecov.io/.
While I can understand that Codecov servers may be down sometimes, I would love to be able to reduce the time to seconds because we have actually have to wait ~10 minutes.

**Comment by Octogonapus** [comment]
This has been a problem with every CodeCov uploader for a long time. It would be great if there was a configuration option to retry the upload x number of times.

**Comment by adamtheturtle** [comment]
<img width="1290" alt="Screenshot 2020-08-18 at 00 03 42" src="https://user-images.githubusercontent.com/797801/90452547-574d3900-e0e6-11ea-9c45-8bbb59f256b3.png">

This just happened again, on 1.0.12, after 11 minutes.

**Comment by mathieu-bour** [comment]
I guess that [v1.0.13](https://github.com/codecov/codecov-action/releases/tag/v1.0.13) solves this, right?

**Comment by kriegfrj** [comment]
> I guess that [v1.0.13](https://github.com/codecov/codecov-action/releases/tag/v1.0.13) solves this, right?

dependabot has just done a PR for us to bump the version to 1.0.13, which I have merged. I guess we'll see how it goes! Thanks to @thomasrockhu for the patch!

**Comment by mathieu-bour** [comment]
However:

> Decrease connection timeouts to 3 seconds and increase attempts to 10 in pulling the bash script

This should limit the duration to approximately 30 seconds. How about make those values configuration like suggested in #113?

**Comment by adamtheturtle** [comment]
I have a repository with >40 jobs in the main CI workflow (https://github.com/VWS-Python/vws-python-mock).
In this repository it was very rare to not see this error on at least one job per run.
In my branch bumping this action to `v1.0.13` the run passed (https://github.com/VWS-Python/vws-python-mock/pull/690).
However, the code coverage is reported as 99.25%, even hours later, and the "missing" coverage is code which I am certain is covered.

For example, https://codecov.io/gh/VWS-Python/vws-python-mock/compare/355730c6297fc61e4cede0f9cdf5dc2e66918e06...143c1ffd35af34b7c14fc3817ddf1e25f31b82f3/src/tests/mock_vws/test_query.py.
This shows that `test_query::TestAcceptHeader::test_valid` is not covered at all.
However, I can see at https://github.com/VWS-Python/vws-python-mock/pull/690/checks?check_run_id=997337082 that the tests ran and passed.
It is as if the coverage report from https://pipelines.actions.githubusercontent.com/24aMLzmFiVrnOAZbDJVsjvzPJ0pTXAUSmss8BIAcQXv2PpCi9Y/_apis/pipelines/1/runs/518/signedlogcontent/18?urlExpires=2020-08-18T12%3A37%3A30.7865207Z&urlSigningMethod=HMACV1&urlSignature=Fu%2FFZ9GTOitbaxKxsPzOvXloNsadurjGE9Qoi68eLHI%3D is not considered.

I can create a different issue for this if appropriate - I would appreciate some advice on this.

**Comment by thomasrockhu** [comment]
@mathieu-bour, I'm going to hold off of making it configurable. The retry logic here is really meant to be a stop-gap to unblock our users using the Action, but the core issues are the same. We are working to fix those instead.

**Comment by thomasrockhu** [comment]
@adamtheturtle, let's solve that on [this thread](https://community.codecov.io/t/long-upload-times-and-timeouts-for-gha-codecov-codecov-action-v1/1588/33) instead.
