### ISSUE TITLE
[Question] What exact things does `codecov-action@v1` do to generate .gcov files in github actions?

### ISSUE THREAD

**Issue by Irving-cl** [codecov/codecov-action#106]
If we use `codecov-aciton@v1` as a step in github actions, what exact steps/commands would it take to generate the `.gcov` report files? I met such a problem: I generate the `.gov` locally, and I check the file, seeing that some code(let's call it **X**) is executed. However, on github-actions, I found that it's not executed.(The repo, build and test are absolutely the same). So is there any way that I could reproduce the actions of `codecov-aciton@v1` locally?

Some background for my project the the tests it executed:
The build and the test of my project is a little bit special. It would be built twice with different options in two different directories. That is to say, there are two different executables in different build directories after the build. Let's called them **A** and **B**. Also, for a source file `a.cpp`, there would be two `a.cpp.gcno` in two different directories. And the test would start and run both executables. 
I'm sure that some code **X** would be executed in **A**. And if I run `gcov` in the build dir of `A`, the `.gcov` file indeed shows that **X** is executed. However, on github actions, the `gcov` shows that **X** is not executed. What could be the reason? Is it possible that **B**'s `gcov` overrides **A**'s?

**Comment by thomasrockhu** [comment]
The GitHub action runs atop the bash uploader. The line that runs `gcov` is [here](https://github.com/codecov/codecov-bash/blob/master/codecov#L1120). You can configure it using the bash uploader instead [here](https://github.com/codecov/codecov-bash/blob/master/codecov#L159)
