### ISSUE TITLE
Coverage contains __init__.py files but codecov report is omitting them

### ISSUE THREAD

**Issue by lexicalunit** [codecov/codecov-action#107]
Starting a little over a week ago `__init__.py` files are removed from codecov reporting.

### Output from my test suite

Showing that `__init__.py` is part of the coverage output, and therefore should be see in the corresponding codecov report.

```
poetry run coverage report -m
Name                                                                                      Stmts   Miss Branch BrPart  Cover   Missing
-------------------------------------------------------------------------------------------------------------------------------------
src/spellbot/__init__.py                                                                    864     21    395     15    97%   487->488, 488, 491->492, 492, 494->495, 495, 498->499, 499, 505->506, 506, 509->510, 510, 513->514, 514, 616->619, 619-624, 1060->1093, 1075->1076, 1076, 1113->1116, 1341->1342, 1342-1344, 1546->1547, 1547-1549, 1581->1578, 1642->1646, 1646
src/spellbot/assets.py                                                                       21      0      2      0   100%
src/spellbot/constants.py                                                                     6      0      0      0   100%
src/spellbot/data.py                                                                        185      0     43      0   100%
src/spellbot/reactions.py                                                                    18      0      4      0   100%
```

### `.coveragerc`

```
[run]
branch = True
source = src/spellbot
omit =
    src/spellbot/_version.py
    src/spellbot/versions/env.py

[report]
ignore_errors = True
exclude_lines =
    pragma: no cover
    raise NotImplementedError
    if __name__ == .__main__.:
```

### `codecov.yml`

None.

### Before 

An example of a good report from a little over a week ago.

- Commit: https://github.com/lexicalunit/spellbot/commit/f21cccdb58700c918f59dbeaa2ebb25752a63c14
- Codecov Report: https://codecov.io/gh/lexicalunit/spellbot/tree/f21cccdb58700c918f59dbeaa2ebb25752a63c14/src/spellbot

See how it contains coverage for `__init__.py`? This is correct.

### After

After changing nothing about `.coveragerc` or my CI configuration, I suddenly started getting reports that are omitting `__init__.py`. For example:

- Commit: https://github.com/lexicalunit/spellbot/commit/ff593b818d42d15bce99137b3d5b809ffe8ef2fc
- Codecov Report: https://codecov.io/gh/lexicalunit/spellbot/tree/ff593b818d42d15bce99137b3d5b809ffe8ef2fc/src/spellbot

Suddenly the `__init__.py` files have just been removed from the codecov report.

### Things I've tried

Adding a `codecov.yml` file with the following contents to the root of my repository.

```yaml
fixes:
  - "::src/spellbot/"
```

- Commit: https://github.com/lexicalunit/spellbot/commit/4c01af61123120a7920526a41c3fbc59716b6401
- Codecov Build: https://codecov.io/gh/lexicalunit/spellbot/commit/4c01af61123120a7920526a41c3fbc59716b6401/build
- Codecov Report: https://codecov.io/gh/lexicalunit/spellbot/tree/4c01af61123120a7920526a41c3fbc59716b6401/src/spellbot/src/spellbot

You can see in the build details that it picked up the `codecov.yml` file. However the report is still omitting the `__init__.py` files.

**Comment by thomasrockhu** [comment]
Thanks @lexicalunit, will take care of [here](https://community.codecov.io/t/init-py-suddenly-being-ignored-in-reports/1855/7)

**Comment by lexicalunit** [comment]
👍 @thomasrockhu, I thought maybe the issue could have been in `codecov/codecov-action` so I figured I'd report it here.
