### ISSUE TITLE
Please provide a timeout argument

### ISSUE THREAD

**Issue by JCMais** [codecov/codecov-action#113]
Most of the time this actions is blazing fast, like less than 10s, but sometimes it takes up to 12 minutes, and most of these times it fails at the end. 

This slowdown deployments and causes unnecessary spending of minutes, it would be helpful if we had an option to stop the action if it takes more than x seconds to run.

Somewhat related issues:
https://github.com/codecov/codecov-action/issues/104
https://github.com/codecov/codecov-action/issues/81

**Comment by thomasrockhu** [comment]
@JCMais, we made some improvements in our system and the underlying bash script. Is this still and issue for you?
