### ISSUE TITLE
Codecov Badge Unknown

### ISSUE THREAD

**Issue by rdmolony** [codecov/codecov-action#118]
[My GitHub repo](https://github.com/codema-dev/drem) uses your codecov action (thanks!) and right now my codecov badge is stuck as Unknown on GitHub for reasons I don't yet understand.

I found [this GitHub thread](https://github.com/nickmerwin/node-coveralls/issues/156) which blames the issue on a communication issue between Travis & GitHub.

(Weirdly the coverage percentage is displayed in my local dev environment )

Do you have any ideas why this might be?

**Comment by thomasrockhu** [comment]
Hi @rdmolony, would you mind opening up a ticket in our [community boards](https://community.codecov.io)? I'm also seeing this:
![image](https://user-images.githubusercontent.com/4213028/91049157-c0531600-e5ea-11ea-9656-a023e1866660.png
