### ISSUE TITLE
__init__.py files are ignored

### ISSUE THREAD

**Issue by ahivert** [codecov/codecov-action#12]
When I use this action, __init__.py files are ignored but all the code is here so coverage become 100%.
I use codecov manually without this action everything works fine.

**Comment by ibrahim0814** [comment]
@ahivert Have you tried using the updated v1.0.3 of this Action. Perhaps that will make a difference. Let me know, otherwise you can always submit a support ticket [here](https://codecov.io/support)

**Comment by ibrahim0814** [comment]
@ahivert We released @v1.0.4 of this action today which resolves a lot of the outstanding issues users were having before. I have a strong hunch that this version might fix your problem

**Comment by ibrahim0814** [comment]
Closing this issue as it's stale
