### ISSUE TITLE
Version `4.0.1` doesn't accept token as parameter

### ISSUE THREAD

**Issue by marekdedic** [codecov/codecov-action#1264]
Hi,
I recently updated the action to v4, added the codecov token as a secret to my repo and I ma passing it to the action as described in the readme - see my config [here](https://github.com/scout-handbook/handbook-api/blob/bcf5264fe4a7ee66a8589bf36bd822239f805d36/.github/workflows/CI.yml#L47-L51). This all works fine with `4.0.0`

However, when trying to update to `4.0.1`, I get `Error: Codecov token not found. Please provide Codecov token with -t flag.` - I think soething is broken between `4.0.0` and `4.0.1` such that the new version doesn't accept the token correctly...

See the update PR [here](https://github.com/scout-handbook/handbook-api/pull/210).

**Comment by tobiasehlert** [comment]
@marekdedic, in the release docs from [v4.0.0](https://github.com/codecov/codecov-action/releases/tag/v4.0.0) under breaking changes it states, that tokenless uploading is unsupported.

**Comment by marekdedic** [comment]
Hi,
yes, I noticed that and added a token, which works for 4.0.0. However, my issue is that 4.0.1 ignores the token...

**Comment by martincostello** [comment]
The token isn't being ignored, it's that Dependabot has no access to it: https://github.com/codecov/codecov-action/issues/1267

**Comment by marekdedic** [comment]
Oh, okay, I'll close this in favor of #1267 - thanks for the clarification :)
