### ISSUE TITLE
Use Node.js 20 for v3

### ISSUE THREAD

**Issue by vkottler** [codecov/codecov-action#1289]
The `v3` action branch triggers the following deprecation warning when used in actions:

```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: codecov/codecov-action@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

([example PR](https://github.com/vkottler/vcorelib/actions/runs/7878114863?pr=136))

Is it viable to update `v3` to use Node.js 20? The `v4` version of this action deletes features compared to `v3`.

**Comment by rohan-at-sentry** [comment]
Hi @vkottler - what features in `v3` are you missing in `v4`?

**Comment by vkottler** [comment]
Per "Breaking Changes" in README.md: `Tokenless uploading is unsupported.`. This broke my projects' actions and I had to migrate from `main` to `v3`.

There doesn't seem to be any compelling reason to set up an API token + store it in a per-repository secret + update action YAMLs so that `codecov-action` will continue performing the exact same task it previously performed without additional requirements.

**Comment by felixfontein** [comment]
Currently v4 is not usable for me in several repos due to #1287.

**Comment by rohan-at-sentry** [comment]
@felixfontein - we'll take a look at what's going on in #1287

**Comment by rohan-at-sentry** [comment]
@vkottler Thanks for clarifying. [For context](https://about.codecov.io/blog/january-product-update-updating-the-codecov-ci-uploaders-to-the-codecov-cli/), we're not actively supporting `v3` beyond critical security fixes. 

The primary rationale around upgrading to v4 and having tokens is around reducing service downtime as a result of Codecov's Github app token being rate-limited. [The token needs to be generated on the Codecov UI and set as a repo secret. ](https://docs.codecov.com/docs/adding-the-codecov-token)

If you have any questions on setting up the token, let us know, we're happy to help

**Comment by vkottler** [comment]
@thomasrockhu-codecov dope!!! It works great thanks for the suggestion and implementation.
