### ISSUE TITLE
Fails on macOS

### ISSUE THREAD

**Issue by paulz** [codecov/codecov-action#13]
macOS build fails:

`##[error]Container action is only supported on Linux`

https://github.com/paulz/ImageCoordinateSpace/commit/4a8530e92f00011b1c8bf8cb1078676b1acc620c/checks#step:5:4

**Comment by adam7** [comment]
Also fails on Windows with the same error.

**Comment by adam7** [comment]
Build failure is because this is a Docker Action which are only supported on Linux. Porting to a JavaScript Action would resolve the issue because they are supported on Windows, macOS and Linux. 

https://help.github.com/en/articles/about-actions#types-of-actions

**Comment by ibrahim0814** [comment]
Hi all,

Copying my answer from #7 here:

> Thank you for bringing this up. I've updated our README to reflect this particular caveat. GitHub currently allows us to build two types of Actions - Docker and JS. We decided to use a Docker action since it allows us to wrap our bash uploader because our bash uploader is the only uploader the Codecov staff actively maintains. Of course, this comes at the cost of sacrificing Windows and macOS build capabilities.
> 
> Perhaps in the future, we will support these other operating systems, but for the time being, I do apologize that this action's functionality is limited to only Linux

Ib

**Comment by adam7** [comment]
Looking at your entrypoint https://github.com/codecov/codecov-action/blob/master/entrypoint.sh all your container does is download and then run a binary which you could just as easily do in a JavaScript Action and would give you cross platform support.

**Comment by ibrahim0814** [comment]
@adam7 I'll look this, I wasn't aware that it was possible but perhaps my assumptions are incorrect here.

**Comment by nklayman** [comment]
Maybe you should add `if: runner.os == 'Linux'` to the readme example for now.

**Comment by ibrahim0814** [comment]
@nklayman I added that line to our readme on [this commit](https://github.com/codecov/codecov-action/commit/8d062b28e11a2e28f19a70e04bc2a125a1f83385)

Thanks for the suggestion!

**Comment by ibrahim0814** [comment]
Hi all,

As of release v1.0.4, we've officially switched to using JavaScript for our action. It is now supported on Linux, macOS, and Windows. Feel free to use it your macOS and matrix builds :D 

@adam7 Thank you for your initial suggestion!

Ib
