### ISSUE TITLE
[v4] Commit creating failed: {"error": "Server Error (500)"}

### ISSUE THREAD

**Issue by flbraun** [codecov/codecov-action#1336]
I'm aware of #1282 , but I'm also receiving this error in a job on an ordinary public repository (https://github.com/boxine/bx_django_utils).

<details>
<summary>Full log of codecov-action</summary>
Run codecov/codecov-action@v4
  with:
    files: coverage
    fail_ci_if_error: true
    verbose: true
  env:
    COVERAGE_FILE: coverage
    pythonLocation: /opt/hostedtoolcache/Python/3.11.8/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.11.8/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.8/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.8/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.8/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.8/x64/lib
    CODECOV_TOKEN: ***
==> linux OS detected
https://cli.codecov.io/latest/linux/codecov.SHA256SUM
Received SHA256SUM 5c8d8ce377f84c043d0ce41bebdc870ee6fb29c47791338899ddbe05bde97df0  codecov
Received SHA256SUM signature -----BEGIN PGP SIGNATURE-----

iQIzBAABCgAdFiEEJwNOf9uFDgu8LGL/gGuyiu13mGkFAmXfdOAACgkQgGuyiu13
mGmCng/+K+OHZYN4lzJFILpizRpZ1y4qqoUXAmANGMBLBKap2zIug6j1LEM9Hprh
0lKxNsjpLTBrL9XxtxJEXwdMMwNpXnu+s4MWNnx6wp52CQKb+TdHVA8M7Oo/kwP0
+zZkcZcc4Ko7nQAUtYA4j82W//TcJzU+CI0CVvioWJ1iPU3Jvi9DzCyiMl5uYLud
UDOQ0xztGgp7YDPjr54jiLdYPHv8tLJXd7It0+ywWs3rG9AHb1jRfW4Q1Ul1G7V3
poTT1YpBcNdQP3faxuAJ+eMB+Sl+44wc3O3BlTFAgoNG53psmjhluSlUmpVZQGvk
gTc8Oabr3Vd2QmJvOu9edgy4SzN45tl4VckmfAX+WqMFbrYc4wQpUgtv/Y4+56c4
1CiUDB9PxwY3sH4riv+p/xknuFTAQwjj/sBB78s+FOjAAKolo5AMUOB6QzA7DA4g
0bVWc11KGP+7SWe45KId1XDn6M5q/6bp2/JA6Akjpm5HE/x/9NSPaXuahQKzqgA0
BW3pS9wsJFnMuovdJxviOmJxnNO1CcYzBTZLYajlPZiU4Dv/0xfhYHTappko4Uqw
waqnrKZxPd/quRQjakJMfluu+obtDRr3YeC3X47h71DNs71i3aVo9MK6Pgq8VOhk
RlZUHytU1xjWE917vqScMpyDlxLFoU5m9shTv0/0YqcT1eNa7hk=
=wyFR
-----END PGP SIGNATURE-----

==> Running version latest
gpg: directory '/home/runner/.gnupg' created
gpg: keybox '/home/runner/.gnupg/pubring.kbx' created
gpg: /home/runner/.gnupg/trustdb.gpg: trustdb created
gpg: key 806BB28AED779869: public key "Codecov Uploader (Codecov Uploader Verification Key) <security@codecov.io>" imported
gpg: Total number processed: 1
gpg:               imported: 1

gpg: Signature made Wed Feb 28 18:01:04 2024 UTC
gpg:                using RSA key 27034E7FDB850E0BBC2C62FF806BB28AED779869
gpg: Good signature from "Codecov Uploader (Codecov Uploader Verification Key) <security@codecov.io>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 2703 4E7F DB85 0E0B BC2C  62FF 806B B28A ED77 9869

==> Running version v0.4.8
==> Running git config --global --add safe.directory /home/runner/work/bx_django_utils/bx_django_utils
/usr/bin/git config --global --add safe.directory /home/runner/work/bx_django_utils/bx_django_utils
==> Running command '/home/runner/work/_actions/codecov/codecov-action/v4/dist/codecov -v create-commit'
/home/runner/work/_actions/codecov/codecov-action/v4/dist/codecov -v create-commit --git-service github -C cbd488536d0d396bdedb9e411014b8f507943694 -Z
==> Uploader SHASUM verified (5c8d8ce377f84c043d0ce41bebdc870ee6fb29c47791338899ddbe05bde97df0  codecov)
info - 2024-03-21 14:18:02,569 -- ci service found: github-actions
debug - 2024-03-21 14:18:02,569 -- versioning system found: <class 'codecov_cli.helpers.versioning_systems.GitVersioningSystem'>
debug - 2024-03-21 14:18:02,570 -- versioning system found: <class 'codecov_cli.helpers.versioning_systems.GitVersioningSystem'>
warning - 2024-03-21 14:18:02,573 -- No config file could be found. Ignoring config.
debug - 2024-03-21 14:18:02,573 -- No codecov_yaml found
debug - 2024-03-21 14:18:02,574 -- Starting create commit process --- {"commit_sha": "cbd488536d0d396bdedb9e411014b8f507943694", "parent_sha": null, "pr": "141", "branch": "unbork-coverage", "slug": "boxine/bx_django_utils", "token": "f******************", "service": "github", "enterprise_url": null}
info - 2024-03-21 14:18:02,678 -- Process Commit creating complete
debug - 2024-03-21 14:18:02,678 -- Commit creating result --- {"result": "RequestResult(error=RequestError(code='HTTP Error 500', params={}, description='{\"error\": \"Server Error (500)\"}'), warnings=[], status_code=500, text='{\"error\": \"Server Error (500)\"}')"}
error - 2024-03-21 14:18:02,678 -- Commit creating failed: {"error": "Server Error (500)"}
Error: Codecov: Failed to properly create commit: The process '/home/runner/work/_actions/codecov/codecov-action/v4/dist/codecov' failed with exit code 1
</details>

**Comment by YunchuWang** [comment]
encountered the same issue when updating to v4. https://github.com/Azure/azure-functions-python-extensions/actions/runs/8456924642/job/23167864539?pr=20
Can we get a fix soon?

**Comment by rohan-at-sentry** [comment]
@YunchuWang @flbraun  - I'm closing this out. Please let me know if this is still happening, we'll investigate.
