### ISSUE TITLE
[v4] Cant upload codecov report anymore: Upload failed: {"error": "Server Error (500)"}

### ISSUE THREAD

**Issue by YunchuWang** [codecov/codecov-action#1346]
https://github.com/Azure/azure-functions-python-extensions/actions/runs/8456924642/job/23167864539?pr=20
![image](https://github.com/codecov/codecov-action/assets/12449837/71b80986-6a64-46bf-a39e-9fc8c7ea1715)

Hi, when we upgrade to v4, we always get this error. The codecov token is added and its not clear from this failure message whats went wrong with upload. We need to exclude tests folder from being covered and only see v4 has the codecov_yml_path setting can allow you to pass in codecov.yml. 

Please investigate and help thank you,
also for v3, is there a way for the action to take in codecov.yml?

**Comment by rohan-at-sentry** [comment]
@YunchuWang is this still happening? If so, can you point me to a latest run with this issue? It's possible that this was before we released some changes that (among other things) added more details on the failure
