### ISSUE TITLE
Please provide a way to disable annotations

### ISSUE THREAD

**Issue by AlekSi** [codecov/codecov-action#135]
Check statuses and report comments are very useful, but "Added lines XXX were not covered by tests" annotations are really annoying. Please provide a way to disable them.

**Comment by thomasrockhu** [comment]
@AlekSi you can disable them [here](https://docs.codecov.io/docs/github-checks-beta#disabling-github-checks-patch-annotations)

**Comment by AlekSi** [comment]
But shouldn't it be documented on https://docs.codecov.io/docs/codecovyml-reference?

**Comment by thomasrockhu** [comment]
Good point @AlekSi, I'll do that today

**Comment by thomasrockhu** [comment]
Updated, thanks again for pointing the documentation issue @AlekSi

**Comment by AlekSi** [comment]
Thank you!
