### ISSUE TITLE
Question: Codecov comments

### ISSUE THREAD

**Issue by marbar3778** [codecov/codecov-action#136]
We updated to 1.0.13 and now there are comments throughout the code in the pull request stating what is covered and what is not. How does one disable this? I could not find anything in the docs

**Comment by thomasrockhu** [comment]
@marbar3778, this is a result of our new [GitHub Checks](https://blog.codecov.io/2020/09/08/announcing-line-by-line-coverage-via-github-checks/) feature. You can find instructions on disabling [here](https://docs.codecov.io/docs/github-checks-beta#disabling-github-checks-patch-annotations)
