### ISSUE TITLE
What does "full functionality" mean?

### ISSUE THREAD

**Issue by mrgrain** [codecov/codecov-action#1399]
Hey team,

The action is including this warning on every comment it is posting on my repos:

> ❗ Your organization needs to install the [Codecov GitHub app](https://github.com/apps/codecov/installations/select_target) to enable full functionality.

Like probably many of you, I am not an organization admin in my GitHub org. So I need to convince my org admins to install the app. When I approach them, the rightfully would like to understand what we are currently missing and what great features constitute "full functionality". Unfortunately the documentation is very silent about this. 

I'd love to convince my org admins to install the app, but for that I will need to know why. Hopefully you can provide us with some insight.

PS: If the answer is "Nothing, but the action might stop working eventually", that's also fine. But it would be great to just be open about it.

**Comment by rohan-at-sentry** [comment]
@mrgrain totally valid.

We're exploring ways to highlight what the full value of Codecov during onboarding. In the meantime (to help convince your org), here's what the Codecov Github App being install unlocks for you and your org. ([you can find this described here](https://github.com/apps/codecov), but I'll expand on the benefits below : 

- By setting up the Codecov Github app, Codecov is now able to track coverage against commits and pulls. This allows your team to track (on the Codecov UI) how coverage changes with each commit/PR
- Codecov is also able to understand your file paths, and with features such as `flags` and `components` allow you to setup coverage reporting based on these paths - useful if you're working with a monorepo, or would benefit from more detailed reporting on a set of filepaths.
- Detailed PR comments and customizable github checks from codecov
