### ISSUE TITLE
Error 500 trying to upload a coverage report

### ISSUE THREAD

**Issue by gcotelli** [codecov/codecov-action#140]
```
==> Uploading to Codecov
curl: (3) [globbing] unmatched close brace/bracket in column 102
    HTTP 500
```
I'm having this error in some of our builds: 
https://github.com/ba-st/Stargate/pull/113/checks?check_run_id=1155856111

**Comment by thomasrockhu** [comment]
Hi @gcotelli, would you mind opening a ticket in the `support` section of our [community boards](https://community.codecov.io) for this?

**Comment by gcotelli** [comment]
Done https://community.codecov.io/t/error-500-trying-to-upload-a-coverage-report/2183
