### ISSUE TITLE
Action does not find reports by glob pattern

### ISSUE THREAD

**Issue by dbeuchler** [codecov/codecov-action#144]
Hi! I have a problem with this action. In my project I generate a lot of `OpenCover.xml` files. These files should be published to codecov. I found out that the action is using the bash script which is supporting a glob pattern `folder/\*.OpenCover.xml*. 

I am using the following action definition:

````yml
- name: Codecov
  uses: codecov/codecov-action@v1
  with:
  files: './artifacts/Tests/*.OpenCover.xml'
````

If the [action runs](
https://github.com/PHOENIXCONTACT/MORYX-Platform/runs/1197445288#step:8:28) it only finds 1 report: 

````text
==> GitHub Actions detected.
    project root: D:/a/MORYX-Platform/MORYX-Platform
    Yaml not found, that's ok! Learn more at http://docs.codecov.io/docs/codecov-yaml
    -> Found 1 reports
==> Detecting git/mercurial file structure
==> Reading reports
    + ./artifacts/Tests/Moryx.Communication.Sockets.IntegrationTests.OpenCover.xml 
````

There are [currently 7 report XML files](https://github.com/PHOENIXCONTACT/MORYX-Platform/runs/1197445288#step:7:70) in this folder, but why are they not found? I already checked the code which is reading the files but do not have found any problems.

**Comment by thomasrockhu** [comment]
Hi @dbeuchler, please open a ticket in the #support section of our [community boards](https://community.codecov.io).
