### ISSUE TITLE
How to disable the checks in PR?

### ISSUE THREAD

**Issue by powerwolf543** [codecov/codecov-action#146]
I triggered this action in my every pushs. If I want to ignore the checks on my PR, what should I do?

**Comment by thomasrockhu** [comment]
@powerwolf543, here's the documentation to [disable comments](https://docs.codecov.io/docs/common-recipe-list#disable-pull-request-comments) and to [disable status checks](https://docs.codecov.io/docs/commit-status#disabling-a-status). Closing this out, but feel free to open a ticket in the `support` section of our [community boards](https://community.codecov.io).

**Comment by powerwolf543** [comment]
@teohhanhui , thank you
