### ISSUE TITLE
Multiple coverage reports for one and the same codebase

### ISSUE THREAD

**Issue by Ch00k** [codecov/codecov-action#149]
I have a project that is tested by two different sets of tests: unit and integration. I would like to generate two different coverage reports for these two sets of tests, and make codecov.io. display them separately. Is this possible?

**Comment by Ch00k** [comment]
I configured CI to send two different coverage files to codecov.io, as can be seen [here](https://codecov.io/gh/Ch00k/orthanc-rest-client/commit/12ad6efe4a3916121ea5c82b75a43156f53da333/build).

**Comment by thomasrockhu** [comment]
@Ch00k, you can use [flags](https://docs.codecov.io/docs/flags) for this. Closing this out, but feel free to open a ticket under `support` in our [community boards](https://community.codecov.io)
