### ISSUE TITLE
Uploading on Windows has silent failure

### ISSUE THREAD

**Issue by dfreilich** [codecov/codecov-action#163]
We use the `codecov-action` in buildpacks/pack ([here](https://github.com/buildpacks/pack/blob/adf080445f36d349b6728f8b4c976cf1bd641c00/.github/workflows/build.yml#L76-L81) is the configuration), and we have noticed of late (around the past month) that it hasn't commented coverage on any PRs. 

Looking into it, it seems that it silently fails to upload on a windows runner, with this error: 
```
Couldn't read data from file "/tmp/codecov.MsdkCD.gz", this makes an empty POST.
```

As an example, see [here](https://github.com/buildpacks/pack/runs/1283513426?check_suite_focus=true). 

Related: https://github.com/buildpacks/pack/issues/906

**Comment by thomasrockhu** [comment]
@dfreilich, thanks for this. Would you be able to open a ticket in our [community boards](https://community.codecov.io)?

**Comment by dfreilich** [comment]
Opened this up: https://community.codecov.io/t/uploading-on-windows-has-silent-failure/2266
