### ISSUE TITLE
codeage data updated to codecov is not correct

### ISSUE THREAD

**Issue by Jokcy** [codecov/codecov-action#167]
https://github.com/pure-vue/vue3-jsonschema-from/runs/1399219764?check_suite_focus=true

in this action, all code of the repo has been tested, but only coveage data of `App.tsx` file uploaded. How can I change the behavior

**Comment by thomasrockhu** [comment]
Hi @Jokcy, please view our [troubleshooting guide](https://docs.codecov.io/docs/troubleshooting-guide) and open a ticket in our [community boards](https://community.codecov.io).
