### ISSUE TITLE
Feature Request: Allow job to be set

### ISSUE THREAD

**Issue by drazisil** [codecov/codecov-action#170]
Ideally I'd like to be able to set the job value to $GITHUB_WORKFLOW, but the option to control it manually would be nice as well.

**Comment by thomasrockhu** [comment]
@drazisil, this isn't even an option on the bash uploader 😆, should we not just add a line that sets it?

**Comment by drazisil** [comment]
I didn't look to see what sets it in the bash uploader,  I only noticed it gets sent as an empty query parameter when used with the action.

I thought the bash uploader had an override already

**Comment by thomasrockhu** [comment]
It should now be set in the bash uploader 😄
