### ISSUE TITLE
Is it possible to make the GitHub Action show as successful even when patch coverage is reduced?

### ISSUE THREAD

**Issue by TheAnnalyst** [codecov/codecov-action#181]

**Comment by thomasrockhu** [comment]
Hi @TheAnnalyst, please ask in our [community boards](https://community.codecov.io), but you can set status checks to [informational](https://docs.codecov.io/docs/common-recipe-list#set-non-blocking-status-checks)

**Comment by TheAnnalyst** [comment]
Okay, thanks!
