### ISSUE TITLE
Exclude files and packages from coverage accounting

### ISSUE THREAD

**Issue by PavelRavvich** [codecov/codecov-action#189]
Origin **codecov** plugin support `ignore `flag for excluding files or packages from test coverage accounting [https://docs.codecov.io/docs/ignoring-paths](url)
But in the input arguments list, no one mentions it. Can I somehow exclude files or packages with current functionality `codecov-action@v1` or it's completely impossible for now?

**Comment by thomasrockhu** [comment]
@PavelRavvich, we will be looking to release this in a v2 release in the next coming weeks. Thanks for pointing this out!

**Comment by thomasrockhu** [comment]
Sorry, I misread this. Ignoring paths is not an argument list, but a section of the [codecov.yml](https://docs.codecov.io/docs/codecovyml-reference#ignore)

**Comment by PavelRavvich** [comment]
> Sorry, I misread this. Ignoring paths is not an argument list, but a section of the [codecov.yml](https://docs.codecov.io/docs/codecovyml-reference#ignore)

Question not about low-level technical implementation details, the question about functionality. Possibility of excluding files. If I understand correctly, I can't use `codecov.yml` and **codecov-action** simultaneously. Are all configuration settings available only with `build.yaml` GitHub Action config?

**Comment by thomasrockhu** [comment]
@PavelRavvich, the `codecov.yml` file is used as a configuration file on how Codecov should work on your coverage (e.g. status checks, files to ignore, PR comment information). The `codecov-action` is the actual actor that uploads coverage reports to Codecov.
