### ISSUE TITLE
Don't rebuild container on each run

### ISSUE THREAD

**Issue by iansu** [codecov/codecov-action#19]
Currently the container is rebuilt each time the action is run which takes about 90 seconds. I think this is a limitation of GitHub Actions but maybe you could upload a built container to Docker Hub or GitHub Package Repository and point at that instead?

**Comment by jjangga0214** [comment]
Yes, that's the right way when using docker on actions. However, I suggest directly using a Virtual Environment of VM. See #21 for more detail.

**Comment by tienvx** [comment]
Duplicate #15

**Comment by iansu** [comment]
Looks like this is a duplicate so I'll close this in favour of #15

**Comment by iansu** [comment]
I solved my own problem by creating a Node version of this action that doesn't require a build step: https://github.com/iansu/codecov-action-node
