### ISSUE TITLE
Bad Request 400

### ISSUE THREAD

**Issue by williamjmorenor** [codecov/codecov-action#191]
There is a Bad Request message failing to upload reports to codecov:

https://github.com/cacao-accounting/cacao-accounting/runs/1630805484?check_suite_focus=true#step:11:44

The workflow file is setup a per docs:

https://github.com/cacao-accounting/cacao-accounting/blob/9fca0faf77e054ad33ec26b7f07bdf98ef1d98b9/.github/workflows/python-package.yml#L69

**Comment by thomasrockhu** [comment]
@williamjmorenor can you run this with the verbose flag on and post to our [community boards](https://community.codecov.io)?
