### ISSUE TITLE
Why don't use Alpine image?

### ISSUE THREAD

**Issue by jjangga0214** [codecov/codecov-action#20]
`ubuntu:latest` is cached in VM ([ref](https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions#ubuntu-1804-lts)). However, it still takes time with high IO.

```
Step 1/6 : FROM ubuntu:latest
latest: Pulling from library/ubuntu
5667fdb72017: Pulling fs layer
d83811f270d5: Pulling fs layer
ee671aafb583: Pulling fs layer
7fc152dfb3a6: Pulling fs layer
7fc152dfb3a6: Waiting
d83811f270d5: Verifying Checksum
d83811f270d5: Download complete
ee671aafb583: Verifying Checksum
ee671aafb583: Download complete
7fc152dfb3a6: Verifying Checksum
7fc152dfb3a6: Download complete
5667fdb72017: Verifying Checksum
5667fdb72017: Download complete
5667fdb72017: Pull complete
```

To shorten this, we can use Alpine.

**Comment by jjangga0214** [comment]
However, after checking what Dockerfile does, I concluded just using VM would be better than docker. See #21.

**Comment by ibrahim0814** [comment]
Thank for bringing this up @jjangga0214 

We do not use Docker in our action as of release version 1.0.4. A number of our users had similar issues regarding slow build times, thus we've converted our action to use JavaScript. It is significantly faster and also supports macOS and Windows builds.
