### ISSUE TITLE
Files Not Being Searched in Specified Directory

### ISSUE THREAD

**Issue by saurabmish** [codecov/codecov-action#206]
As per the documentation,

`directory` is the directory to search for coverage reports, and `files` is the comma-separated paths to the coverage report(s).

If I'm specifying the `directory` as `./tests/coverage/`, followed by `file` as `coverage.xml`, Im seeing a message `- file not found at coverage.xml`. **See the** "Publish Coverage Report" section in [this workflow](https://github.com/saurabmish/Data-Structures-and-Algorithms/runs/1752197290?check_suite_focus=true).

Changing the value of `file` to `./tests/coverage/coverage.xml` works. 

But the first case should also work since I'm specifying the directory which contains the report and the name of the report.

**Comment by thomasrockhu** [comment]
@saurabmish, would you mind running the above in `verbose` mode and opening a ticket in our [community boards](https://community.codecov.io)

**Comment by saurabmish** [comment]
Done. [Link](https://community.codecov.io/t/whats-the-point-of-using-directory-if-the-complete-path-to-has-to-be-provided-in-files/2493)
