### ISSUE TITLE
Failed to generate report: No data to report

### ISSUE THREAD

**Issue by yooksi** [codecov/codecov-action#215]
I am using `codecov-action` plugin for the first time and am receiving the mentioned error. 
My workflow setup has been mostly copy-pasted from the example given in `README`.

- Workflow file: [`cd-workflow`](https://github.com/yooksi/pz-zdoc/blob/b77f417872cccf18d765e88799d1b2c273c31282/.github/workflows/cd-workflow.yaml)

- Failed run: [`Java CD \#10`](https://github.com/yooksi/pz-zdoc/runs/1868201582?check_suite_focus=true#step:11:56)

```
Coverage.py warning: No data was collected. (no-data-collected)
============================= test session starts ==============================
/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/pytest_cov/plugin.py:271: PytestWarning: Failed to generate report: No data to report.

  self.cov_controller.finish()
platform linux -- Python 3.7.9, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /home/runner/work/pz-zdoc/pz-zdoc
plugins: cov-2.11.1
collected 0 items
WARNING: Failed to generate report: No data to report.
```

**Comment by thomasrockhu** [comment]
This looks like an issue with `coverage.py` as you are not actually collecting data there.
