### ISSUE TITLE
403 when trying to add codecov github action to public repo

### ISSUE THREAD

**Issue by alethenorio** [codecov/codecov-action#221]
I have tried to add codecov to a public repository however when the github action runs, it receives a 403

See the PR in question which adds the github action

https://github.com/einride/balena-go/pull/7/checks?check_run_id=1903359075

I am uncertain what the issue is here as we have done this for other public repositories before without any issues.

Any ideas on what is going on here?

**Comment by thomasrockhu** [comment]
@alethenorio, can you add the `verbose` flag so we can get more details? Also please note the error [here](https://github.com/einride/balena-go/pull/7/checks?check_run_id=1903359075#step:6:24).

Please feel free to use our [community boards](https://community.codecov.io) for this kind of ask. Closing out here, but feel free to open on the boards and link to this issue.
