### ISSUE TITLE
action success but no reports

### ISSUE THREAD

**Issue by yi-Xu-0100** [codecov/codecov-action#222]
https://github.com/yi-Xu-0100/conventional-commit-types-i18n/actions/runs/568724343

https://codecov.io/gh/yi-Xu-0100/conventional-commit-types-i18n/commit/31522f965e1d67dc4fb841dba10cc2803b3638b7

https://github.com/yi-Xu-0100/conventional-commit-types-i18n/actions/runs/568766637

https://codecov.io/gh/yi-Xu-0100/conventional-commit-types-i18n/commit/d8f3c36da989b07ca24aa0491432e7528e8bb76f

https://github.com/yi-Xu-0100/conventional-commit-types-i18n/actions/runs/568799365

https://codecov.io/gh/yi-Xu-0100/conventional-commit-types-i18n/commit/ebce39c4b52cff25c8127b0012db1b4e7482da6e

The coverage report can be seen in local.

**Comment by yi-Xu-0100** [comment]
It says: "There was an error processing coverage reports."

But I don't know how to find it.

**Comment by thomasrockhu** [comment]
@yi-Xu-0100, you will need path fixes likely, try adding the below to your `codecov.yml` file.

```
fixes:
  - "lib/::"
```

If you are still having issues, please open a ticket in our [community boards](https://community.codecov.io) instead.
