### ISSUE TITLE
Upload coverage reports even if there are test failures

### ISSUE THREAD

**Issue by bhathiya** [codecov/codecov-action#229]
It seems Codecov doesn't upload reports if there are test failures, even though Jacoco has them generated. I want to upload them regardless of test failures. I couldn't find any arguments in the README.md to change this behaviour. Is there a way I can do this?

Thanks,
Bhathiya

**Comment by thomasrockhu** [comment]
@bhathiya, please open a ticket in our [community boards](https://community.codecov.io). This sounds like a GitHub Actions issue as opposed to a Codecov specific one, though.

**Comment by bhathiya** [comment]
Thanks for the response Thomas.

**Comment by bhathiya** [comment]
You were right @thomasrockhu. Got it fixed with this[1].

![image](https://user-images.githubusercontent.com/3960742/109101576-fc5b6500-774c-11eb-92bb-c1056dc3a17a.png)

[1] https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#job-status-check-functions

**Comment by thomasrockhu** [comment]
Oh nice find @bhathiya! Thanks for posting back your solution.
