### ISSUE TITLE
Stuck on "Waiting for CI to complete"

### ISSUE THREAD

**Issue by Jean85** [codecov/codecov-action#239]
I work on multiple projects that use this action to upload, and I'm getting "Waiting for CI to complete" on many of them right now.

At first I was getting the "Unable to find commit in Github" error, but I fixed it as said in https://github.com/codecov/codecov-action/issues/190#issuecomment-753547785, but then, once I solved that, the "Waiting for CI to complete" message was still stuck there.

Examples:
 * https://codecov.io/gh/facile-it/terminable-loop-command/commit/57477c064319844cf53e3ebcbc5893f515b6afec/
 * https://codecov.io/gh/getsentry/sentry-symfony/commit/32fce0e687afb835505ec759de9fe1225b9d4d94/

**Comment by thomasrockhu** [comment]
@Jean85 apologies, can you open a ticket in our [community boards](https://community.codecov.io)?

**Comment by Jean85** [comment]
Done https://community.codecov.io/t/stuck-on-waiting-for-ci-to-complete/2676

**Comment by thomasrockhu** [comment]
Closing as this has been solved in the above community ticket
