### ISSUE TITLE
Use codecov action with a C++ project

### ISSUE THREAD

**Issue by skypjack** [codecov/codecov-action#24]
I'm interested in porting a project that uses coveralls to codecov and therefor I'd like to use this action.
However, I'm struggling with the workflow file because I don't understand how to generate a proper report to send remotely.
Is there any example or have you any hint in this sense?

Thank you.

**Comment by hootener** [comment]
@skypjack is this example helpful: https://github.com/codecov/example-cpp11-cmake. Essentially you want to generate (with lcov) the coverage.info file, or (without lcov) automatically using gcov. You can see these steps outlined in the linked example. 

The action comes into play when you're performing the actual upload. So the action should replace the bash uploader step in the given examples for TravisCI in the above repo.

**Comment by skypjack** [comment]
I saw the example but it's not that useful. It discusses travis rather than GH actions and what you do in the former cannot be ported 1-to-1 on the latter.
Btw I went [the hard way](https://github.com/skypjack/entt/blob/master/.github/workflows/coverage.yml) and made it work finally. Howver, a more integrated solution would be really appreciated.
Any plan to release your own action for that?

**Comment by ibrahim0814** [comment]
@skypjack Have you tried using the latest version of this Action that we released today? (@v1 or @v1.0.4)
Perhaps that might resolve some of the issues you've encountered.

**Comment by skypjack** [comment]
I'd be glad to test it for you. Have you tried this version on the linux vm already?

**Comment by ibrahim0814** [comment]
Yes, it's been tested on our sample repo with linux, windows, and macos builds

**Comment by ibrahim0814** [comment]
Closing this issue as it's stale

**Comment by skypjack** [comment]
Hi, yeah, sorry, I've been busy during the last weeks and haven't had yet the time to try it.
I'll do it asap and let you know. I'll reopen the issue if it doesn't work eventually.
Thanks for your time.
