### ISSUE TITLE
Switching default branch seems to have broken things

### ISSUE THREAD

**Issue by JustinBeckwith** [codecov/codecov-action#242]
Greetings folks, and thank you for a lovely GitHub Action!  A few weeks ago I switched the default branch in my project from `master` to `main`.  Everything with the transition seems to be working, except for code coverage.  

My usage of the GitHub Action is pretty basic:
https://github.com/JustinBeckwith/linkinator/blob/main/.github/workflows/ci.yaml#L31

Yet the dashboard, it shows nothing:
https://app.codecov.io/gh/JustinBeckwith/linkinator/

This used to work perfectly fine when I was on the `master` branch, so I'm fairly certain it has something to do with that transition.  Forgive me if this isn't the right place to post, but it felt like a good place to start :)

**Comment by thomasrockhu** [comment]
@JustinBeckwith, I think you will need to add

```
with:
  fetch-depth: 2
```
[here](https://github.com/JustinBeckwith/linkinator/blob/main/.github/workflows/ci.yaml#L18) for `actions/checkout`

**Comment by prescottprue** [comment]
@thomasrockhu - that fixed an issue that just started appearing for us where the action returned the error "invalid request parameters" on a workflow that has been working for months. I think it would be go to have this added to [the example in the README](https://github.com/codecov/codecov-action/blob/master/README.md#example-workflowyml-with-codecov-action)

**Comment by JustinBeckwith** [comment]
Y'all I suspect this is on me.  Turns out I never had the action working properly to begin with, and had to revert to the npm module.

**Comment by helpermethod** [comment]
> @JustinBeckwith, I think you will need to add
> 
> ```
> with:
>   fetch-depth: 2
> ```
> 
> [here](https://github.com/JustinBeckwith/linkinator/blob/main/.github/workflows/ci.yaml#L18) for `actions/checkout`

@thomasrockhu Is this still needed? Somehow I never had a problem with fetch-depth `1`.

**Comment by thomasrockhu** [comment]
@helpermethod I made some changes to the GitHub Action that should make this unnecessary now.
