### ISSUE TITLE
Yaml from subfolder not uploaded

### ISSUE THREAD

**Issue by jotoeri** [codecov/codecov-action#262]
Seems to me like a bug:

On the linked workflow run, having the codecov.yml in a subfolder `tests/codecov.yml`, the action seems to recognize the yml-file. 
However, if i open the corresponding ci-processing, that is also linked at the end of the action, then codecov tells me that no yaml has been found.
It works flawless, if i have codecov.yml in the project-root folder.

https://github.com/nextcloud/forms/runs/2217668623 - Section ' Upload coverage' 
![grafik](https://user-images.githubusercontent.com/47433654/112828752-6d65a380-9090-11eb-9ab7-143a140a2652.png)

https://codecov.io/gh/nextcloud/forms/commit/6186a255db8e554be224edb78154514871f5e4d9/build
![grafik](https://user-images.githubusercontent.com/47433654/112828832-879f8180-9090-11eb-9eb4-02717c049591.png)

**Comment by thomasrockhu** [comment]
@jotoeri, although the uploader can access the file, our servers require the yaml to be located in the root, `dev/`, or `.github/` folders

https://docs.codecov.io/docs/codecov-yaml#can-i-name-the-file-codecovyml

**Comment by jotoeri** [comment]
Oh, ok. So then i missed that. 🙈 Thanks for your response! :)
