### ISSUE TITLE
Invalid request parameters

### ISSUE THREAD

**Issue by geirolz** [codecov/codecov-action#272]
Hi I'm having some troubles with my open source project. 
I'm trying to upload coverage date to codecov but I get this error `Invalid request parameters`.

It this a but or I missing something ? 
Thank you for the support 

CI config file:
https://github.com/geirolz/advxml/blob/master/.github/workflows/ci.yml

Sceen:
<img width="1357" alt="Screenshot 2021-04-09 at 18 14 51" src="https://user-images.githubusercontent.com/31506564/114209946-7d6a6680-995f-11eb-8185-e881cadca6e4.png">

**Comment by thomasrockhu** [comment]
@geirolz sorry for the delay here. Can you open a ticket in our [community boards](https://community.codecov.io) for this?
