### ISSUE TITLE
Support for fully-qualified Windows paths for 'files' input

### ISSUE THREAD

**Issue by natescherer** [codecov/codecov-action#273]
Hello,
Based on my testing, it appears that this action cannot accept fully-qualified Windows paths (i.e. `C:/foo/bar/coverage.xml`) for the files input. Could this support please be added? I'm using the following to convert it before I pass the path, but it would be nice if the action could support it directly.
```
cygpath -u 'C:/foo/bar/coverage.xml'
```
Thanks for the great action and platform!

**Comment by thomasrockhu** [comment]
@natescherer could you open a ticket for this in our [community boards](https://community.codecov.io) so we can better track this request? If you have a repository that exhibits the incorrect behavior, that would be extremely useful.
