### ISSUE TITLE
Question: How to make action only warn but not fail?

### ISSUE THREAD

**Issue by rejas** [codecov/codecov-action#274]
Hi,
in https://github.com/MichMich/MagicMirror this codecov action is used, but sometimes a PR is trivial and doesnt change the test coverage. Still our codecov action fails and reports an error. Is there a way to make the action only warn and not fail?
See https://github.com/MichMich/MagicMirror/blob/master/.github/workflows/codecov-test-suites.yml
Thanks in advance for the help

**Comment by thomasrockhu** [comment]
@rejas I think you're looking for [informational status checks](https://docs.codecov.io/docs/commit-status#branches). You can update the Codecov yaml with the above info.

**Comment by rejas** [comment]
Thanks for the hint, but does that mean I have to add a codecov.yaml to the project? Currently we dont have one, only the github action which doesnt seem to have that informational flag.

**Comment by thomasrockhu** [comment]
@rejas yes, you will need to add it to the root, `dev/` or `.github/` folders.

**Comment by rejas** [comment]
Thx for the help, will do!
