### ISSUE TITLE
Why do you store bash script on your website rather to store it within image?

### ISSUE THREAD

**Issue by umed** [codecov/codecov-action#28]

**Comment by ibrahim0814** [comment]
Hi @umed

Good q! Calling to codecov.io/bash ensures that the action is always using the most up to date version of the bash script without us having to push updates to the action itself. If we ever want to update the bash uploader, we simply push changes to codecov.io/bash and those changes automatically propagate out to anything using the uploader (including this action)

Let me know if I've sufficiently answered your question or if you need me to elaborate more

Ib

**Comment by umed** [comment]
Hi @ibrahim0814 ,

I think you've answered my question. Thanks!
