### ISSUE TITLE
Checksum should be run on bash uploader script before execution

### ISSUE THREAD

**Issue by ebpetway** [codecov/codecov-action#281]
Codecov.io announced today that their bash uploader script had been comprimised: https://about.codecov.io/security-update/ . 
A checksum should be run against the bash uploader script before execution as a precaution: https://docs.codecov.io/docs/about-the-codecov-bash-uploader#validating-the-bash-script.

**Comment by krassowski** [comment]
Indeed, it is very surprising to see no mitigation applied after reading the security update. It seems that https://github.com/codecov/codecov-action/blob/master/src/index.ts was not modified since they learned about the attack, so codecov-action is still vulnerable.

**Comment by jromero** [comment]
Do we know the extent of the effect on usage within GitHub Actions? If I'm not mistaken secrets (env vars) aren't automatically passed to the github action container that runs a step ([see docs](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsenv)).

Does that mean that any secrets are likely not to have been leaked unless you explicitly added secrets to your env vars for this step (aka action) or the [top-level](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#env)?

**Comment by krassowski** [comment]
> Does that mean that any secrets are likely not to have been leaked unless you explicitly added secrets to your env vars for this step (aka action) or the top-level?

See official guide on [Security hardening for GitHub Actions](https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions):

> The individual jobs in a workflow can interact with (and compromise) other jobs. For example, a job querying the environment variables used by a later job, writing files to a shared directory that a later job processes, or even more directly by interacting with the Docker socket and inspecting other running containers and executing commands in them.

> **This means that a compromise of a single action within a workflow can be very significant, as that compromised action would have access to all secrets configured on your repository**, and can use the GITHUB_TOKEN to write to the repository. Consequently, there is significant risk in sourcing actions from third-party repositories on GitHub. You can help mitigate this risk by following these good practices:

IMO you should rotate all secrets for all repos that used codecov-action between January and April.

**Comment by Firehed** [comment]
I'm personally quite surprised (and, in this context, disappointed) to learn that this action uses the bash uploader at all. Given that so much of the CI pipeline is known for actions to run, I feel that a more direct upload without all of the auto-detection code in the bash script would be _far_ safer, and users of the action could be a lot more secure through version pinning of the action itself.

But yes, at absolute minimum, this action should follow Codecov's own best practices regarding script validation.

**Comment by thomasrockhu** [comment]
Tom from Codecov here. We will be working on getting checksum validation in this Action as quickly as possible.

**Comment by gbaydin** [comment]
This repo seems to officially belong to the codecov.io team.

Given this, I think that there should be no reliance in this repo on the bash uploader setup `bash <(curl -s https://codecov.io/bash)` pulled on-the-fly from the codecov website. The idea to "directly and blindly execute a bash script pulled from the web" is giant security hole and a ticking bomb for future breaches.

Like @Firehed above I'm surprised and disappointed that this is used here at all.

If I were working for codecov, I would push for a setup where we maintain a mirror of the latest uploader code somewhere in this repo without any bash script pulled online. Perhaps I'm missing something.

**Comment by thomasrockhu** [comment]
Thanks for the suggestion @gbaydin, it's a great idea. I'll update the script to do that this week.

**Comment by haampie** [comment]
So, thanks for doing something @thomasrockhu, but could you please put the checksums inside the repo instead of downloading them from an external URL? It defies the point of checksum verification.

Just create a versioned URL for your bash script, version the github action accordingly, and put the checksum inside this repo.

See also https://github.com/codecov/codecov-bash/pull/426

**Comment by thomasrockhu** [comment]
@haampie thanks here, I updated on the most recent version of the action `1.4.1.`

**Comment by haampie** [comment]
Thanks!

**Comment by rarkins** [comment]
Did 1.4.0 have *broken* checksum checks?

**Comment by thomasrockhu** [comment]
@rarkins it did not, but the checksums were pulled from `github`, and `1.4.1` stores them in the action

**Comment by rarkins** [comment]
So if the 1.4.0 action reported hours ago that the sha values mismatch and to contact codecov security then it's not a false positive?

**Comment by thomasrockhu** [comment]
@rarkins it is not a security issue. The `1.4.0` pulls the latest SHASUMs which include the `env` script. That file is not used by the Action, so it shows up as a mismatch.

If you look at the output, the SHASUMs should match on the `codecov` script

**Comment by rarkins** [comment]
It sounds like you'd be better off admitting clearly that 1.4.0 was buggy instead of giving the community doubts that codecov's bash script has been compromised again. The action literally told us to contact security (which I've done) and the warning was shared widely throughout our company.

**Comment by thomasrockhu** [comment]
@rarkins I take the blame that `1.4.0` was not compatible with the new bash script. It should not have triggered an action to contact `security@codecov.io`, and that is greatly my fault.

**Comment by roll** [comment]
> IMO you should rotate all secrets for all repos that used codecov-action between January and April.

It seems to be a good idea. Although based on the knowledge of what the modification was my guess that it didn't really break into github secrets not included into a codecov step as an env
