### ISSUE TITLE
Codecov suddenly stopped working

### ISSUE THREAD

**Issue by oeddyo** [codecov/codecov-action#283]
From this morning, Codecov was not triggered for any PR. Anyone knows what's going on?

**Comment by thomasrockhu** [comment]
@oeddyo are you using the [app integration](https://github.com/apps/codecov)? This is a known issue when our servers are getting rate-limited, and using the integration alleviates that communication.

**Comment by oeddyo** [comment]
Yes I'm using app integration:
![image](https://user-images.githubusercontent.com/1943146/114913684-559f5680-9dd6-11eb-9ff9-d8feda5dc98d.png)

**Comment by oeddyo** [comment]
FWIW I saw the banner this morning and also rotated my CODECOV_TOKEN. I hope it's irrelevant to the issue I saw here though. Now whenever I push and generate a PR, the codecov test is simply not triggered :(

**Comment by thomasrockhu** [comment]
@oeddyo, got it. Would you mind opening up a ticket in our [community boards](https://community.codecov.io), and I can take a look?
