### ISSUE TITLE
Codecov showing Unable to find report content in the storage archive

### ISSUE THREAD

**Issue by oeddyo** [codecov/codecov-action#285]
No response from support emails... Also saw it on the community forum. The status check seems fine so I think some of your engineers should notice this: 

![image](https://user-images.githubusercontent.com/1943146/115150455-5675f980-a01d-11eb-8e7a-ada86feb8e42.png)

**Comment by thomasrockhu** [comment]
@oeddyo, looks like this was on our end. We've cleared this up for future PRs and commits and apologies for the issue.

**Comment by oeddyo** [comment]
Thanks! @thomasrockhu
