### ISSUE TITLE
Action failed - Codecov 1.0.2 checksums for SHA1 failed to match

### ISSUE THREAD

**Issue by jimsmart** [codecov/codecov-action#289]
Hi,

I have a repo that was using `codecov-action@v1.4.0`

Builds started failing just a short while ago — despite me not having had set `fail_ci_if_error: true`

The error message was:

```
Warning: Codecov 1.0.2 checksums for SHA1 failed to match.
Public checksum:   537069158a6f72b145cfe5f782dceb608d9ef594  codecov
af0dd19ee59f977bf5793cffafe116d7c248aa62  env
Uploader checksum: 537069158a6f72b145cfe5f782dceb608d9ef594  codecov
Error: Codecov failure: Bash script checksums do not match published values. Please contact security@codecov.io immediately.
Error: Codecov failed with the following error: Codecov failure: Bash script checksums do not match published values. Please contact security@codecov.io immediately.
```

Switching my workflow to use `codecov-action@v1.4.1` fixed the problem.

No idea yet if this effects my other repos that are using 1.4.0 :/

**Comment by jimsmart** [comment]
I realise this may be to do with the update you pushed earlier today, and possibly some caching somewhere (maybe on GitHub's side, who knows?) — but it's kinda rude to have it kill the whole build.

**Comment by thomasrockhu** [comment]
@jimsmart apologies this was written to prevent another issue last week and was written more in haste than it should have been. Bumping to `1.4.1` should fix the issue as you mentioned.

**Comment by jimsmart** [comment]
Do updates to codecov-action versions always break previous working versions like this? — or have I just been unlucky with my timing when adding this to a whole heap of repos? 😢

**Comment by thomasrockhu** [comment]
@jimsmart no, this was definitely unintentional and a mistake on my end. I'm so sorry for the inconvenience.

**Comment by jimsmart** [comment]
Ah, ok, understood, no worries — filed under "-it happens" 😉 

Cheers

**Comment by thomasrockhu** [comment]
Thanks for understanding @jimsmart, let me know if you run into any other troubles
