### ISSUE TITLE
Request impact analysis with GitHub Actions per Codecov Bash Uploader Security Update 

### ISSUE THREAD

**Issue by webstoreportal** [codecov/codecov-action#291]
https://about.codecov.io/security-update/

Discussion 

For more context, assurance and searchability

See [What is the Codecov Bash Uploader?](https://about.codecov.io/security-update/#:~:text=What%20is%20the%20Codecov%20Bash%20Uploader?)
> ## What is the Codecov Bash Uploader?
> In the case of some third party integrations, the bash uploader is used to provide the core upload functionality needed to properly integrate with Codecov. These uploaders include:
> * Codecov-action for Codecov Github Action

**Comment by thomasrockhu** [comment]
@webstoreportal please email security@codecov.io for any further details regarding your situation.

**Comment by trung** [comment]
I think [this commit](https://github.com/codecov/codecov-action/commit/ce1ffb8db73e6493b6b8c7dda270236aba77f05d) would already mitigate the issue and it's available in 1.4.1.
