### ISSUE TITLE
Malware Bytes - classification error?

### ISSUE THREAD

**Issue by askusWT** [codecov/codecov-action#294]
Ref attached Malware Bytes report claiming **trojan** on codecov.io

**Approach to Replicate**
install malware bytes, navigate to any codecov.io page on regular web

**See attached screenshot**

**Commentary** 
Little to say about this except 

- I don't believe it, 
- and there's sadly no good info in the logs to suggest why MWB is classifying you as such
- and I can't confirm whether this is just some quirk in my settings (**warning potential red herring**) or more general.

But I thought you'd want to know anyway.

![Screenshot 2021-04-26 16 31 00](https://user-images.githubusercontent.com/63749667/116110236-693b9e80-a6ad-11eb-808b-6b3c633a1f8f.png)

**Comment by thomasrockhu** [comment]
Thanks @askusWT. We have contacted them about the block, and it should be lifted within the hour. When you get a chance, could you do the following actions to see if it's still there?

```
1. Open Malwarebytes
2. Click the gear icon at the upper right
3. Go to the General tab
4. Click on where it says "Check For Updates"​
```
