### ISSUE TITLE
[FR?] Uploading reports as archive

### ISSUE THREAD

**Issue by LebedevRI** [codecov/codecov-action#324]
This is either a feature request, or a documentation request.
The native https://github.com/codecov/codecov-bash uploads
each report separately, which doesn't quite scale well with
large report number. I'm seeing that the upload takes
an extremely long time. It would perhaps be good to be able
to archive the reports first, and upload them in one go.

Is that something that can be done?

X-Ref https://github.com/codecov/codecov-bash/issues/437

**Comment by thomasrockhu** [comment]
@LebedevRI if you are using GitHub Actions, you can do something like [this](https://about.codecov.io/blog/uploading-code-coverage-in-a-separate-job-on-github-actions/). If you have other questions, feel free to open a ticket in our [community boards](https://community.codecov.io)

**Comment by LebedevRI** [comment]
I'm sorry, but i fail to see how that answers my question.

**Comment by LebedevRI** [comment]
I'm sorry, i should have been more specific.

It looks like my problem is that in https://github.com/darktable-org/rawspeed/runs/2705949853?check_suite_focus=true "Upload coverage report" the `==> Reading reports` takes most of the time, not the upload itself.
It kinda makes sense, since the `codecov` is a bash script, and that is windows,
which is famously known for having pretty bad performance for starting new executables...

**Comment by thomasrockhu** [comment]
Ahhhh I see @LebedevRI. That is a significant number of files. We don't truly support it, but you might be interested in the [exe](https://github.com/codecov/codecov-exe) uploader.
