### ISSUE TITLE
Codecov can't find additional coverage files if defined manually

### ISSUE THREAD

**Issue by fizyk** [codecov/codecov-action#325]
I've got several files that I want to send coverage to codecov 
However, if I define the list manually, the codecov action for github actions only finds the first, stating that the rest is not there.
https://github.com/ClearcodeHQ/pytest-mysql/pull/310/checks?check_run_id=2713352743

Leaving it for codecov to figure out which files to upload actually works

https://github.com/ClearcodeHQ/pytest-mysql/pull/310/checks?check_run_id=2713338180

Which is a bit odd. And makes me think that I need to change all the previous projects I migrated to codecov 🤔

**Comment by jharley** [comment]
Confirmed this is still a thing and this "fix" worked 🤔
