### ISSUE TITLE
find: 'gcov': No such file or directory

### ISSUE THREAD

**Issue by isbadawi** [codecov/codecov-action#34]
I tried to use this action on my C project and I got this:

https://github.com/isbadawi/badavi/commit/f14ae4f61dbed2b28c7a4c05168e3da3b26abc5e/checks?check_suite_id=315103590

```
==> GitHub Actions detected.
    project root: .
    Yaml found at: .codecov.yml
==> Running gcov in . (disable via -X gcov)
find: 'gcov': No such file or directory
find: 'gcov': No such file or directory
find: 'gcov': No such file or directory
==> Python coveragepy not found
==> Searching for coverage reports in:
    + .
--> No coverage report found.
    Please visit http://docs.codecov.io/docs/supported-languages
Codecov upload failed
```

It looks like `gcov` is not installed in the image. I worked around it by [manually invoking the bash uploader](https://github.com/isbadawi/badavi/commit/ce9f937214ff55696a572dfff209af70c28cd533) -- I guess the GitHub-hosted environment has `gcov`.

Successful invocation: https://github.com/isbadawi/badavi/commit/ce9f937214ff55696a572dfff209af70c28cd533/checks?check_suite_id=315119018

**Comment by ibrahim0814** [comment]
@isbadawi I'm sorry to hear you had trouble with gcov. Have you tried using the latest version (codecov-action@v1.0.4 or codecov-action@v1)? 

We updated this Action so that it doesn't use Docker images anymore

**Comment by isbadawi** [comment]
After experimenting more with actions I decided to just upload a manually-generated coverage report as an artifact. So I haven't tested v1.0.4, but I imagine it'll work.
