### ISSUE TITLE
Pull version information from package.json, running `npm run build` produces unwanted changes

### ISSUE THREAD

**Issue by filbranden** [codecov/codecov-action#343]
Hi @thomasrockhu!

I was going to create a pull request for this, but in my local setup when I run `npm i` followed by `npm run build` I get many spurious unrelated changes in `dist/index.js`, mostly a diff that starts with `var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {` and goes on from there, many times in the file. I tried this in two separate machines and have had the issue on both... Not sure if your machine setup is different and is picking up a different component version? Anyways, maybe take a look at whether you need to update some component in package.json or similar to ensure generation of `dist/index.js` is consistent.

The suggestion I was going to make is:

```js
diff --git a/src/buildExec.ts b/src/buildExec.ts
index edb614f..2dbf0a4 100644
--- a/src/buildExec.ts
+++ b/src/buildExec.ts
@@ -1,7 +1,7 @@
 const core = require('@actions/core');
 const github = require('@actions/github');
 
-import VERSION from './version';
+const pjson = require('../package.json');
 
 const context = github.context;
 
@@ -59,7 +59,7 @@ const buildExec = () => {
       '-F',
       `${flags}`,
       '-Q',
-      `github-action-${VERSION}`,
+      `github-action-v${pjson.version}`,
   );
 
   const options:any = {};
```

Which reads the "version" field from package.json, so you could remove `src/version.ts` altogether and keep the version string in a single place. (BTW, I found this suggestion in [this StackOverflow answer](https://stackoverflow.com/a/10855054/9447571).)

Feel free to push a commit with this change if you like the idea. Or let me know if you manage to figure out if something was missing in package.json to make generation consistent and I can send a PR then.

Cheers!
Filipe

**Comment by RA80533** [comment]
It looks like you did the same thing I just did. Kudos.

The only thing I did differently is use the ECMAScript module syntax for importing the manifest. Troubleshooting questions have been getting out of date quite fast so it's important to take into account the context in which an answer was written.

For a Node.js project that relies on the use of the CommonJS module system (in other words, the older module system specific to Node.js), using `require()` to load the manifest makes sense. It's what's available. The answer was written in 2012, however, so it's left out various nuances in behavior such as the bare import pattern causing issues with tree-shaking functionality (e.g., the import is not desctructured before it's assigned—this has an impact on module optimization), nor does it suggest the use the newer ECMAScript module system.

Anyway, I hope that better resources and more up-to-date information is able to outpace the somewhat distracting outdated information. Hopefully this gave you an idea for what to look for next time you're looking at Node.js resources.

**Comment by RA80533** [comment]
@filbranden With regards to the build step, did you receive the same diff between systems? If not, that's a big issue because it means the build step is non-deterministic for some reason.

**Comment by filbranden** [comment]
> With regards to the build step, did you receive the same diff between systems? If not, that's a big issue because it means the build step is non-deterministic for some reason.

Same diff on both systems. But I still get it, I wonder why you don't...

From a fresh checkout:

```
$ npm i

> yarn@1.22.10 preinstall /home/filbranden/devel/codecov-action/node_modules/yarn
> :; (node ./preinstall.js > /dev/null 2>&1 || true)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.2.0 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.2.0: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 787 packages from 420 contributors and audited 790 packages in 9.089s

42 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

Then:

```
$ npm run build

> codecov-action@1.5.2 build /home/filbranden/devel/codecov-action
> ncc build src/index.ts

ncc: Version 0.22.3
ncc: Compiling file index.js
ncc: Using typescript@4.3.2 (local user-provided)
 55kB  dist/codecov
267kB  dist/index.js
322kB  [3050ms] - ncc 0.22.3
```

(Note, it says "typescript@4.3.2 (local user-provided)" but that's the version I see in the package.json)

And then the diff:

```
$ git diff
diff --git a/dist/index.js b/dist/index.js
index 244651b..8ef93d7 100644
--- a/dist/index.js
+++ b/dist/index.js
@@ -54,6 +54,25 @@ module.exports =
 
 "use strict";
 
+var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
+    if (k2 === undefined) k2 = k;
+    Object.defineProperty(o, k2, { enumerable: true, get: function() { return m[k]; } });
+}) : (function(o, m, k, k2) {
+    if (k2 === undefined) k2 = k;
+    o[k2] = m[k];
+}));
+var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
+    Object.defineProperty(o, "default", { enumerable: true, value: v });
+}) : function(o, v) {
+    o["default"] = v;
+});
+var __importStar = (this && this.__importStar) || function (mod) {
+    if (mod && mod.__esModule) return mod;
+    var result = {};
+    if (mod != null) for (var k in mod) if (k !== "default" && Object.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
+    __setModuleDefault(result, mod);
+    return result;
+};
 var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
     function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
     return new (P || (P = Promise))(function (resolve, reject) {
...
```

Versions of components I have (not sure if those matter):

```
$ node -v
v14.17.0
$ npm -v
6.14.13
```

Any idea what might be causing this? I'm happy to help investigate, but I'm not ultra familiar with all the components here so not really sure what might be causing the differences in my local environment...

**Comment by RA80533** [comment]
Sorry, I may have not explained it well enough. I do get the changes.

**Comment by RA80533** [comment]
@thomasrockhu Could it have been possible that the full file wasn’t committed but only portions of it were? It appears that happened in a few of the more recent commits, especially those relating to `version`.

**Comment by filbranden** [comment]
I see this snippet (`text: "\n            var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {\n`) in `node_modules/typescript/lib/tsserverlibrary.js`, so I guess that's part of typescript@4.3.2.

I wonder if that "(local user-provided)" means it might use a local version if available and if @thomasrockhu might have a different version installed and that's causing the difference?

**Comment by thomasrockhu** [comment]
@filbranden @RA80533 sorry ya'll, I was offline for a bit. That looks very suspicious, running `npm run build` I see

```
--> npm run build

> codecov-action@1.5.2 build /Users/thomashu/src/github/codecov/codecov-action
> ncc build src/index.ts

ncc: Version 0.22.3
ncc: Compiling file index.js
ncc: Using typescript@4.1.5 (local user-provided)
```

For what it's worth, 

```
--> node -v
v12.18.4
--> npm -v
6.14.6
```

**Comment by thomasrockhu** [comment]
Bumping up to `4.3.2` locally gives me a huge diff too, I'm going to move the build step into CI so that we don't run into this issue again.

**Comment by thomasrockhu** [comment]
Bumping to `4.3.2` gives me the same issue, I'm going push up a commit to fix this for now and noodle on how to get this into CI later.

**Comment by thomasrockhu** [comment]
See this [pr](https://github.com/codecov/codecov-action/pull/358)

**Comment by thomasrockhu** [comment]
Thank you all for the investigative work and the amateur hour of the wrong dependency

**Comment by filbranden** [comment]
Was that the typescript you had installed locally on your host?

From https://github.com/vercel/ncc/blob/main/src/typescript.js, it looks like it might pick a locally installed one if the `TYPESCRIPT_LOOKUP_PATH` environment variable is set... Perhaps it would be worth unsetting this variable as part of the `npm run build` command to ensure it picks the one managed by npm? (Or perhaps there's a better/more elegant solution to that that I'm not aware of...)

**Comment by filbranden** [comment]
There's also this:
https://github.com/vercel/ncc#with-typescript

That section also says "If typescript is found in `devDependencies`, that version will be used", but here it's listed in `dependencies`. Not sure if this matters, and if moving it to `devDependencies` would ensure the one managed by npm is always used?

**Comment by RA80533** [comment]
Yeah, it doesn’t look like the dependencies are set correctly anyway for the project. The manifest file needs to be refactored at least once to get everything straightened out.

@thomasrockhu What we’re the steps you used to bump your local installation of TypeScript? Can you check to see if it’s the same install you get if you were to do it fresh from the repository?

**Comment by RA80533** [comment]
```console
rm -rf node_modules
npm install
```

**Comment by thomasrockhu** [comment]
@RA80533 working on doing a refactor now. As for bumping local installation, I don't have the exact steps, but likely from doing bumping my `npm` installation and re-running `npm install`

**Comment by RA80533** [comment]
Can you try to remove the node_modules folder and run installation again? npm takes into account the shape of the node_modules folder when trying to determine what to install. In other words, it’s behavior is partially determined by node_modules. You want a fresh installation at every point you can get.

**Comment by RA80533** [comment]
Additionally, I sent an email to tom @ your organization. Was this you? If not, could you send me a quick message at gRA80533 @ Google’s email service?

**Comment by thomasrockhu** [comment]
@RA80533 I have done so
```
--> node -v
v14.17.0
--> npm -v
6.14.13
--> rm -rf node_modules
--> npm install
```

Also, just responded to your email. As for the deps, I opened [this PR](https://github.com/codecov/codecov-action/pull/359)

Is there anything else I'm missing here? There are a few threads running, and I don't want any to get lost.
