### ISSUE TITLE
Requires cURL

### ISSUE THREAD

**Issue by mxcl** [codecov/codecov-action#349]
This is pretty strange requirement considering this is a JavaScript action.

Either way you should *at least* specify this requirement in the README. It’s trivial to use this action in a Docker container that has no cURL.

However if you want some actual geek points, drop the requirement for cURL. Like aren’t you guys a profitable business?

**Comment by RA80533** [comment]
I'd file that over in [codecov-bash](https://github.com/codecov/codecov-bash) since that's what's responsible for that area. The script seems to be manually duplicated over in this one so it isn't quite clear to onlookers that this is actually two separate projects.

**Comment by thomasrockhu** [comment]
This should be resolved in `v2`
