### ISSUE TITLE
index.ts will not exit with an failure status code even if Bash does

### ISSUE THREAD

**Issue by RA80533** [codecov/codecov-action#352]
~~The only place in which index.ts will correctly signal an error through its exit status code is if the call to `unlink()` fails.~~

EDIT: index.ts checks the truthiness of `failCi` to determine whether it should signal an error. Unfortunately, since `failCi` is shadowed (see #351), this will never be the case because `failCi` will never be defined in the correct scope.

**Comment by thomasrockhu** [comment]
This should be fixed now that `failCi` is not shadowed.
