### ISSUE TITLE
I/O is synchronous

### ISSUE THREAD

**Issue by RA80533** [codecov/codecov-action#353]
Synchronous I/O is often the source of problems relating to leaky error handling. Additionally, Node.js is not able to take advantage of its strong asynchrony if I/O is handled in a synchronous manner.

- https://github.com/codecov/codecov-action/blob/29386c70ef20e286228c72b668a06fd0e8399192/src/index.ts#L14
- https://github.com/codecov/codecov-action/blob/29386c70ef20e286228c72b668a06fd0e8399192/src/index.ts#L21
- https://github.com/codecov/codecov-action/blob/29386c70ef20e286228c72b668a06fd0e8399192/src/index.ts#L36

Related #352

**Comment by thomasrockhu** [comment]
I think this should no longer be a problem as the `fs.*` code has been removed.
