### ISSUE TITLE
Unrecoverable states are not handled

### ISSUE THREAD

**Issue by RA80533** [codecov/codecov-action#354]
This is the area responsible for handling any errors thrown from `readFileSync()`:

https://github.com/codecov/codecov-action/blob/29386c70ef20e286228c72b668a06fd0e8399192/src/index.ts#L15-L19

If the function were to throw an error indicating that the file could not be written, execution would still continue. The call to `exec()` would then attempt to execute whatever exists at the path of `filepath`, regardless of whether or not a file was written there.

**Comment by thomasrockhu** [comment]
Fixed via https://github.com/codecov/codecov-action/pull/364
