### ISSUE TITLE
Permit dashes in input flags

### ISSUE THREAD

**Issue by alalazo** [codecov/codecov-action#36]
Currently if I try to use flags that have a dash this action will fail to upload after several retries. On the last one it will display this message:
```console
flags must match pattern ^[\w\,]+$
```
This issue is basically a request to permit dashes (and maybe other characters too?) in the flags attached to the uploaded report. This will allow users to employ as a flag:
```yaml
flags: ${{ matrix.os }}
```
which currently resolves to names like `ubuntu-latest` or `windows-latest`.

**Comment by ibrahim0814** [comment]
Thanks for bringing this up @alalazo! We noticed that there were some regex pattern matching issues involved with permitting dashes for flags, though we'll definitely explore this further to see if we can implement it

**Comment by hershmire** [comment]
Any update on this? We just ran into this issue as well when using hyphens for the `-F` flag value.

**Comment by thomasrockhu** [comment]
@hershmire, flags should be allowed to have dashes and periods now.
