### ISSUE TITLE
Run on Node.js 14

### ISSUE THREAD

**Issue by RA80533** [codecov/codecov-action#363]
https://github.com/codecov/codecov-action/blob/ae8835afc44d3128c7b51d08093474ac596e8ab4/action.yml#L102

**Comment by thomasrockhu** [comment]
I don't believe this is possible yet. See https://github.com/codecov/codecov-action/pull/359/checks?check_run_id=2803642925#step:6:1

![image](https://user-images.githubusercontent.com/4213028/121699404-e4f67c80-ca9c-11eb-9227-14beed8a16df.png)

**Comment by RA80533** [comment]
Gotcha. Looks like that will be the compilation target.
