### ISSUE TITLE
Files not showing up as covered

### ISSUE THREAD

**Issue by neutrinoceros** [codecov/codecov-action#393]
Hi,
I've attempted to use this action to auto-upload reports to Codecov.io in the following PR
https://github.com/SydneyAstrophotonicInstrumentationLab/AMICAL/pull/52

However, on the web interface, it looks like only the tests/ folder of the project is covered, while when I produce a local report,
I get a much different picture
<img width="703" alt="Screenshot 2021-06-24 at 18 59 11" src="https://user-images.githubusercontent.com/14075922/123303609-451a0380-d51e-11eb-91d3-c1b4ffa9fecf.png">

I've been trying to understand what I've been doing wrong but the setup is identical to other projects I have where this works perfectly, with the only difference being that I'm not the owner of this project (but the owner _did_ setup authorisations properly, I believe). Is there anything faulty on our side ? is this a bug in the GitHub action ?

Thank you

**Comment by thomasrockhu** [comment]
@neutrinoceros closing this out, could you open a ticket on our [community boards](https://community.codecov.com)
