### ISSUE TITLE
Restrict force pushes

### ISSUE THREAD

**Issue by RA80533** [codecov/codecov-action#395]
This restriction is automatically applied to every branch matching a branch protection pattern. The `*` wildcard pattern can be used to match every branch of the repository, including those of PRs.

This configuration can be implemented through the following branch protection ruleset:

> #### Branch name pattern
> `*`
> #### Rules applied to everyone including administrators
> - (*Unchecked*) Allow force pushes

**Comment by thomasrockhu** [comment]
@RA80533, I know a common workflow is to force push on top of your own branch. I'd rather have this unchecked on `master` only
