### ISSUE TITLE
Require signed commits on the main branch (`master`)

### ISSUE THREAD

**Issue by RA80533** [codecov/codecov-action#396]
Enforcing cryptographic verification of commits helps maintain the cryptographic integrity of the project by preventing unverified commits from affecting the codebase.

This configuration can be implemented through the following branch protection ruleset:

> #### Branch name pattern
> `master`
> #### Protect matching branches
> - (*Checked*) Require signed commits
> - (*Checked*) Include administrators

**Comment by thomasrockhu** [comment]
Done, thanks @RA80533
