### ISSUE TITLE
"Codecov: Uploader shasum does not match uploader hash" 

### ISSUE THREAD

**Issue by MarcinOrlowski** [codecov/codecov-action#437]
I am facing `Codecov: Uploader shasum does not match uploader hash` trying to use literaly copy-paste GitHub Action example setup.

```
 Warning: Unexpected input(s) 'path_to_write_report', valid inputs are ['token', 'files', 'directory', 'flags', 'commit_parent', 'dry_run', 'env_vars', 'fail_ci_if_error', 'file', 'functionalities', 'move_coverage_to_trash', 'name', 'override_branch', 'override_build', 'override_commit', 'override_pr', 'override_tag', 'root_dir', 'slug', 'url', 'verbose', 'working-directory']
Run codecov/codecov-action@v2
  with:
    token: ***
    directory: ./coverage/reports/
    env_vars: OS,PYTHON
    fail_ci_if_error: true
    files: ./coverage.xml
    flags: unittests
    verbose: true
  env:
    OS: windows-latest
    PYTHON: 3.7
    pythonLocation: C:\hostedtoolcache\windows\Python\3.7.9\x64
==> SHASUM file signed by key id 806bb28aed779869
D:\a\_actions\codecov\codecov-action\v2\dist\codecov.exe -n codecov-umbrella -Q github-action-2.0.1 -e OS,PYTHON -Z -f ./coverage1.xml -f ./coverage2.xml -F unittests -s ./coverage/reports/ -v

     _____          _
    / ____|        | |
   | |     ___   __| | ___  ___ _____   __
   | |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
   | |___| (_) | (_| |  __/ (_| (_) \ V /
    \_____\___/ \__,_|\___|\___\___/ \_/

  Codecov report uploader 0.1.0
Error: Codecov: Uploader shasum does not match uploader hash: 
b703b68634be7ee137d78fc3d152598b9ece064482f31964177ae6ea0028a0c0  codecov.exe,  public hash:
80c66284a12e9ada7a8da2f223600e3e4826a7e5e2249887d0859fa5447f1122  codecov.exe
```

**Comment by cheginit** [comment]
I am facing the same issue. It's not consistent though. Some CIs pass some don't. For example, you can see [this](https://github.com/cheginit/async_retriever/runs/3126373873?check_suite_focus=true) Github Actions workflow.

**Comment by thomasrockhu** [comment]
This looks like a race condition during release. The SHA it's comparing to is the latest, but we are pulling a slightly older SHA. It should resolve within the hour, but I'll work on making sure it doesn't happen on future releases.

**Comment by xenova** [comment]
I'm also experiencing the same issue.

**Comment by thomasrockhu** [comment]
@xenova apologies, we still haven't figured out how to remove the race condition. We expect it to clear up in the next half hour.

**Comment by xenova** [comment]
Googling "Error: Codecov: Uploader shasum does not match uploader hash: " returns quite worrisome results.
https://thenewstack.io/not-your-usual-supply-chain-hack-the-codecov-bash-uploader-blunder/
https://news.ycombinator.com/item?id=26819983

Is this a similar issue?

**Comment by thomasrockhu** [comment]
@xenova It is very unlikely. We currently have a race condition when we release a new version of the uploader and all of the SHASUMs are uploaded to https://uploader.codecov.io. You can view them to verify that they are showing the previous version's sha as opposed to the latest.

I'm sorry, I know this is an unnecessary cause for concern, but thank you for following up here.

**Comment by MarcinOrlowski** [comment]
I am no longer having reported issue. I will leave this opened as I see others joined. Whoever maintains - Feel free to close at will.

**Comment by thomasrockhu** [comment]
We have pushed a fix for this which should resolve on future uploader pushes. I will close when we release a new version of the uploader (not the Action) and no further issue occurs.

**Comment by thomasrockhu** [comment]
Closing this out as another uploader version has been published without changes here.

**Comment by Jolg42** [comment]
Just happened today in this run https://github.com/prisma/prisma/runs/3291354178 

Using `- uses: codecov/codecov-action@v2`

Workflow file here https://github.com/prisma/prisma/blob/main/.github/workflows/test.yml

**Comment by thomasrockhu** [comment]
@Jolg42 got it, I'll sync up with our team to see why this is still happening
