### ISSUE TITLE
Codecov still searches in all directories even if `files` argument given

### ISSUE THREAD

**Issue by melink14** [codecov/codecov-action#442]
Since files is an explicit list of coverage files, I was surprised to see codecov searching in all directories for coverage files after adding it.

And if it did find other coverage files that I didn't specify it seems counter intuitive that those files would be included in addition to the ones I specified expliciltly.

Example Run:
https://github.com/melink14/rikaikun/pull/630/checks?check_run_id=3139488305

**Comment by thomasrockhu** [comment]
@melink14, yes we do that to pull the current `network` files (how we match up files in a coverage report to those in a repository). You can kill it by doing `functionalities: network` in the `action` call
