### ISSUE TITLE
Github actions output of coverage url

### ISSUE THREAD

**Issue by nuhkoca** [codecov/codecov-action#46]
Hello,

I am generating a code coverage with your action and the action produces a link in where I can check coverage result lastly. Along with Github Actions we are able to get outputs such as links. For instance, **build scan** generates a link that includes build result and I can get output link as follows.

`steps.<steps_id>.outputs.build-scan-url`

Do you support such method to provide a link of coverage result like

`steps.<steps_id>.outputs.codecov-url`

It would be great for me to share a link with my team. 

Thanks,

**Comment by kierangillblueberry** [comment]
@nuhkoca did you find a workaround for this? We're looking for the same functionality.
