### ISSUE TITLE
Need help: how to set parameter "file" for multiple reports

### ISSUE THREAD

**Issue by AllForNothing** [codecov/codecov-action#47]
In my case, there are two coverage reports(UI_coverage.xml and Back_end_coverage.xml)。

The Doc. says:
![image](https://user-images.githubusercontent.com/30999793/72676398-d4222100-3acb-11ea-84da-c3edd5c56609.png)

I think it means that multiple reports are supported,
so I set "file" parameter like this:
![image](https://user-images.githubusercontent.com/30999793/72676582-b786e880-3acd-11ea-9b37-8d527c86090b.png)
 And it could not work,  what should I do?
![image](https://user-images.githubusercontent.com/30999793/72676617-282e0500-3ace-11ea-8232-b182b5c5a6c4.png)

Thanks

**Comment by Jeckerson** [comment]
According to their [bash script](https://codecov.io/bash) that _eats_ that file(s), you need to use pattern.
In your case: `file: ./*_coverage.xml`

![image](https://user-images.githubusercontent.com/3289702/72685167-29b3f900-3adf-11ea-9aaf-7a7fe7aa4398.png)

**Comment by ibrahim0814** [comment]
@AllForNothing Still having trouble with this?

**Comment by Tyrrrz** [comment]
Is `*.foo` recursive?

I have 2 test projects in separate directories and they produce their separate reports like so:

```
|__ ProjA.Tests
    |__ CoverageOutput.xml
|__ ProjB.Tests
    |__ CoverageOutput.xml
```

What's the best way to match it so I can upload reports in one go?

**Comment by Jeckerson** [comment]
@Tyrrrz 

```
file: ./Proj*.Tests_coverage.xml
```
