### ISSUE TITLE
Conflicting error messages

### ISSUE THREAD

**Issue by piraka9011** [codecov/codecov-action#49]
I'm using the action to generate a codecov report for PRs [here](https://github.com/ros-tooling/system_metrics_collector/pull/78).

However, I'm getting the following error:

```
Yaml found at: ./codecov.yml
sed: can't read ././codecov.yml: No such file or directory
    -> Found 1 reports
==> Detecting git/mercurial file structure
==> Reading reports
    - file not found at ros2_ws/lcov/total_coverage.info
--> No coverage data found.
```

1. Why is codecov saying that it found the file and then `sed` can't read it?
2. Why does codecov say it found the file and then report that there is no coverage (when the coverage was in fact generated?

Thanks

**Comment by zillionare** [comment]
same issue here. Why this issue is closed?

**Comment by thomasrockhu** [comment]
I'm not quite sure to be honest, but this shouldn't be an issue anymore as the uploader does not read nor take into account the `yaml` (this is done server-side)
