### ISSUE TITLE
Incorrect handling of PR builds from GitHub Actions.

### ISSUE THREAD

**Issue by drazisil** [codecov/codecov-action#52]
Summary from the customer:

>  I did a bit of looking today. It appears that `pull_request` events use an automatic merge commit for the pull request, and the GITHUB_SHA is showing that commit hash instead of the one for the commit on the branch that was actually pushed. It makes some sense, but it's a big odd to get your head around. I believe that Travis CI does the same thing, except that they make it easy to know what the underlying commit you're trying to test about is, but GitHub actions does not expose that in an environment variable.

>In order to trace it back to the commit we're really trying to identify, we need to look at the parents of the commit we're on. I'm not sure the optimal way to do that, but the commit message of the current commit has it, and of course git itself has record of what the parent commits are as well, though I'm not totally sure the best way to figure out which of the parents is really the one we're looking for.

It seems that GitHub Actions may make a merge commit build for PRs, similar to how Travis CI does. I'm not sure if they commit this SHA, but the Codecov action does not use the correct SHA in this case.

**Comment by armano2** [comment]
@drazisil this action is just a wrapper for https://codecov.io/bash and this seems to be similar issues to one from pipelines https://github.com/codecov/codecov-bash/issues/189
`pr` property is no being set

**Comment by drazisil** [comment]
This one is different in the sense that we aren't sure if Actions has an env for the PR number.

**Comment by drazisil** [comment]
@ibrahim0814 are you able to chime in here?

**Comment by armano2** [comment]
actions have `GITHUB_REF` and in case of PR its set to `refs/pull/:prNumber/merge`

https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#pull-request-event-pull_request
