### ISSUE TITLE
undefined: command not found

### ISSUE THREAD

**Issue by tenhobi** [codecov/codecov-action#54]
Hi, in build https://github.com/felangel/bloc/actions/runs/36031254, job https://github.com/felangel/bloc/runs/432647943?check_suite_focus=true we are facing `codecov.sh: line 1: undefined: command not found`. (might be relevant to https://github.com/codecov/codecov-action/issues/48)

![image](https://user-images.githubusercontent.com/5287596/74064601-4ca53f00-49f3-11ea-8d85-c4a137b692e2.png)

and Actions tells this

![image](https://user-images.githubusercontent.com/5287596/74064778-adcd1280-49f3-11ea-8e59-e82e69fb310e.png)

It has been randomly appearing across the action runs. From the log, this is an error from your action.

Note that this specific coverage file does not exist, but that should not throw this error I believe. Other jobs where the file also doesn't exist does this (correctly):

![image](https://user-images.githubusercontent.com/5287596/74064707-8c6c2680-49f3-11ea-8816-2555dbd78a19.png)

**Comment by tenhobi** [comment]
There is an example with another build where a different one job had this issue. For now, it was a project which HAD this file but failed to upload it, which is, therefore, a SEVERE BUG.

![image](https://user-images.githubusercontent.com/5287596/74082814-ff11ec00-4a5d-11ea-8b2f-13ec710a06c4.png)

https://github.com/felangel/bloc/runs/433135688?check_suite_focus=true

**Comment by fastcat** [comment]
Seeing the same issue in my project too, e.g. https://github.com/fastcat/wirelink/pull/11/checks?check_run_id=437670014#step:12:9

**Comment by bastimeyer** [comment]
Also just run into this issue after migrating to codecov/codecov-action@v1 and trying to adjust the `after_n_builds` config to the same number of test/coverage jobs that are run for limiting the PR comment spamming.
https://github.com/streamlink/streamlink/pull/2862#issuecomment-609001381

**Comment by bastimeyer** [comment]
Btw, in order to fix this, you should add a retry-loop for downloading the codecov bash script:
https://github.com/codecov/codecov-action/blob/v1.0.6/index.js#L26

And maybe also not rely on `request`, as it's deprecated.
https://github.com/request/request/issues/3142

**Comment by thomasrockhu** [comment]
Hi all, closing this out due to age, and likely has been fixed. If this is wrong, please open a ticket in our [community boards](https://community.codecov.io)
