### ISSUE TITLE
Implement tokenless mode

### ISSUE THREAD

**Issue by webknjaz** [codecov/codecov-action#55]
Newly released API should make this possible: https://github.blog/2020-02-06-manage-secrets-and-more-with-the-github-actions-api/

**Comment by SVilgelm** [comment]
Duplicate of the #29

**Comment by ibrahim0814** [comment]
Hi @webknjaz!

Thanks for bringing this up. I've addressed this in #29, but good news is that we just deployed tokenless for GitHub Actions today! Happy uploading!

Ib
