### ISSUE TITLE
Add support for optional directory 

### ISSUE THREAD

**Issue by jwillemsen** [codecov/codecov-action#57]
We are using codecov in a build which uses multiple source repositories (which we clone in addition to the default one) for which we upload codecov results for each repository. For this an optional 'directory' flag would be helpful, the action should do a cd to the specified directory before running the codecov.sh bash script

**Comment by jwillemsen** [comment]
See https://community.codecov.io/t/how-to-use-codecov-when-having-multiple-git-repositories/955 for some discussion about we use this now without a github action

**Comment by ibrahim0814** [comment]
Hi @jwillemsen, just to clarify, you're talking about having an input to specify the directory in which to search for coverage reports right? If so, I can definitely work to add in that feature soon

**Comment by jwillemsen** [comment]
Yes, we checkout multiple git repositories, in each directory we need to run codecov with a different token and different yml file, given the example below, we want to run it 4 times, each time in a different sub directory, each directory having its own token and its own unique git repo
```
axcioma
taox11
ciaox11
dancex11
```

**Comment by kuromukira** [comment]
Hi @ibrahim0814 , don't want to be rude or anything, but I just wanna ask about any update on this? Thanks.

**Comment by thomasrockhu** [comment]
Hi @jwillemsen, we implemented a `working-directory` argument. Would this solve your case?

**Comment by jwillemsen** [comment]
Thanks, I will try that @thomasrockhu and let you know the results

**Comment by jwillemsen** [comment]
Looks I need to do much more before being able to test this, we are currently not using codecov on github actions because of this restriction, everything now runs on our internal jenkins setup. Looks working-directory is what I need, so closing this, thanks!

**Comment by jo-rdan** [comment]
> Hi @jwillemsen, we implemented a `working-directory` argument. Would this solve your case?

Where to find this?
