### ISSUE TITLE
v1 tag invalid name

### ISSUE THREAD

**Issue by peaceiris** [codecov/codecov-action#59]
@ibrahim0814 
I think `v1` is correct, not `@v1`

<img width="619" alt="Screen Shot 2020-03-05 at 15 54 45" src="https://user-images.githubusercontent.com/30958501/75955651-aa954b80-5ef9-11ea-8099-a0c0a9a2c206.png">

**Comment by ibrahim0814** [comment]
Good catch, changing this right now

**Comment by ibrahim0814** [comment]
Changed, `v1` should now be updated to the latest release

**Comment by peaceiris** [comment]
LGTM. Thank you.
