### ISSUE TITLE
Better documentation: e.g. which rules are used to "auto detect" coverage reports? How does this interact with arguments

### ISSUE THREAD

**Issue by fingolfin** [codecov/codecov-action#644]
A recent change in `codecov-action@v2` (?? update from v0.1.15 to v0.1.16 ???) apparently caused our CI uploads to be incomplete (see https://github.com/gap-system/gap/issues/4752 ; a file named `gap-coverage.json` used to be uploaded, but isn't anymore). 

This made me realize that the documentation (well, the README at https://github.com/codecov/codecov-action) doesn't really explain how things work:
- which files are "autodetected" for upload?
- how does this interact with the `files` argument: are files I list there uploaded *in addition* to auto detected files? or does this argument disable auto detection?
- the same question about the `directory` argument
- ... and also how `directory` and `files` interact

**Comment by sschuberth** [comment]
> which files are "autodetected" for upload?

I guess that's this list:

https://github.com/codecov/uploader/blob/b561fe71e0262aa606b7391014ff01228adfac3d/src/helpers/files.ts#L155-L179
