### ISSUE TITLE
Doesn't fail CI when coverage drops

### ISSUE THREAD

**Issue by YonatanKra** [codecov/codecov-action#674]
I've setup the action and made coverage drop by 10%.
The CI passed even though the flag to fail the CI is on.
How can I make the CI fail if coverage drops below the target?
Here's the relevant PR: 
https://github.com/Vonage/vivid-3/pull/254

**Comment by mehq** [comment]
any update on this? facing the same issue

**Comment by YonatanKra** [comment]
@mehq - the issue was that I did not have the [`codecov` app](https://github.com/apps/codecov) authorized by my organization. Once it was authorized, it started working.

**Comment by asarkar** [comment]
@YonatanKra Is there any reason to keep this ticket open if your problem was solved?
