### ISSUE TITLE
error uploading codecov report

### ISSUE THREAD

**Issue by shahzebsiddiqui** [codecov/codecov-action#677]
i need help with codecov report upload. For some reason its not working with github action see https://github.com/buildtesters/buildtest/runs/5606098670?check_suite_focus=true. I am working on this in this PR https://github.com/buildtesters/buildtest/pull/1028 and trying out a few different things by adding `verbose: true` and changing the version.

I can confirm at end of my regression test there is a `coverage.json` file that is uploaded but i cant get this uploaded. I even added a `token` field and updated the secret in my project to see if that will work but its not picking up the report. If i understand i dont need to specify the `files` to search where coverage report is, this action should just pick it up automatically so i dont understand whats the deal.

I need your help. Please advise what i can do to fix this.

Note i am able to get coverage report working from my gitlab pipelines see https://github.com/buildtesters/buildtest/blob/devel/.gitlab/cori.yml#L25-L26 in my gitlab project i can see
![Screen Shot 2022-03-18 at 4 14 12 PM](https://user-images.githubusercontent.com/12942230/159077027-1d51a1d6-9075-4e77-abfa-53b007cb8b18.png)

**Comment by shahzebsiddiqui** [comment]
@thomasrockhu can u please help me with this issue. I am having hard time getting codecov working with pushing results.

**Comment by shahzebsiddiqui** [comment]
hi @thomasrockhu yeah there was one test that failed but if you look at the other test they are failing on codecov step. I can run the regression test see https://github.com/buildtesters/buildtest/runs/7119499259?check_suite_focus=true


![Screen Shot 2022-06-30 at 4 35 05 PM](https://user-images.githubusercontent.com/12942230/176773637-e83574eb-2cce-4dbb-b4ed-4bff6361b07f.png)

We have a python script https://github.com/buildtesters/buildtest/blob/devel/buildtest/tools/unittests.py that will call coverage module.

The actual lines responsible for coverage are these. I can confirm there is a `coverage.json` but it doesn't get picked up. It is generating this at the root of repo.


https://github.com/buildtesters/buildtest/blob/a22565da72578f6ea3ec27b5ab3a8b37750b139b/buildtest/tools/unittests.py#L69-L79

**Comment by shahzebsiddiqui** [comment]
You can see this PR https://github.com/buildtesters/buildtest/pull/1028 where I am trying to troubleshoot this in the CI job but no luck. I have tried to `cat coverage.json` and i see file exist. I noticed this started to fail at some point not sure when but dependabot starts sending PRs with new changes so not sure if this broke on a particular version of codecov or it just my workflow. Your help would be appreciated.

**Comment by shahzebsiddiqui** [comment]
I know this was working because we got codecov bot notifying on PRs and this only happened after report was published to codecov.io. See https://github.com/buildtesters/buildtest/pull/925. 

So looking at my history we were using version 2.1.0 some time back in this regression workflow from buildtest tag v0.12.0 https://github.com/buildtesters/buildtest/blob/v0.12.0/.github/workflows/regression.yml 

Did something break in recent version?

**Comment by thomasrockhu** [comment]
Sorry @shahzebsiddiqui, but I mean the last 3 commits you sent all have failing tests before coverage can be sent to Codecov. We don't hold logs long enough for me to see what might be wrong before that time.

**Comment by shahzebsiddiqui** [comment]
we were able to figure this out. Closing this issue
