### ISSUE TITLE
Relative path

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [codecov/codecov-action#75]
I am getting this error when I try to see a file in the codecov website:
```
Is the path ... a relative path in your repository?
```
Some time ago it was working without applying any fix. Why is it happening now?

**Comment by AaronJan** [comment]
Same problem at first, but I checked it again after 20 mins or so, it works fine. 

I think there is a timing issue somewhere.

**Comment by thomasrockhu** [comment]
@JavierSegoviaCordoba, is this still an issue?

**Comment by lumbric** [comment]
There is already a [support ticket in the community board](https://community.codecov.io/t/code-file-coverage-report-github-api-forbidden-is-the-path-a-relative-path-in-your-repository/615). Seems that there are troubles again. I can access [a numpy file on Github](https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/alloc.c), but the [correlating codecov page says](https://codecov.io/gh/numpy/numpy/src/master/numpy/core/src/multiarray/alloc.c):

> Is the path `numpy/core/src/multiarray/alloc.c` a relative path in your repository?
