### ISSUE TITLE
Specify report with -J flag

### ISSUE THREAD

**Issue by Kaspik** [codecov/codecov-action#76]
Hey!

Is there a way to specify App/Framework name with `-J "AppName"` as it is in the bash uploader?

`hint Speed up Swift processing by using use -J 'AppName' (regexp accepted)`

Thanks!

**Comment by Jeehut** [comment]
Same here, would be great to have that option, especially given that a warning/hint is printed.

**Comment by thomasrockhu** [comment]
I'll be deploying this sometime next week, thanks!
