### ISSUE TITLE
Specify Derived Data path

### ISSUE THREAD

**Issue by Kaspik** [codecov/codecov-action#77]
Hey!

Is there a way to specify path to the derived data? For example building the tests and their coverage to local folder instead of default Derived data path?

`DerivedData folder: /Users/administrator/Library/Developer/Xcode/DerivedData`

Thanks!

**Comment by thomasrockhu** [comment]
Hi @Kaspik, I'm not exactly sure what you're asking for here. Can you provide more details about what you mean?

**Comment by Kaspik** [comment]
Hey, I'm not sure either anymore. 😂 will close as codecov works for us for months.
