### ISSUE TITLE
Why stuck in "Waiting for CI to complete"?

### ISSUE THREAD

**Issue by SkyeBeFreeman** [codecov/codecov-action#772]
CodeCov is stuck in "Waiting for CI to complete. Please review report with caution, it may change. " and the report doesn't comment in the PR. Can you help me? [CodeCov result](https://codecov.io/github/Tencent/spring-cloud-tencent/commit/02bed159e0141e1f4351b74a7b2f9b98471bcac7).

**Comment by umarmughal824** [comment]
I am facing the same error. Did you find any solution for it?

<img width="1440" alt="Screenshot 2022-07-31 at 11 37 10 PM" src="https://user-images.githubusercontent.com/4043989/182040562-c2399547-8f9b-456b-90db-1070e08d48fc.png">

**Comment by sanwan** [comment]
Me too .

**Comment by SkyeBeFreeman** [comment]
It seems no solution here.
