### ISSUE TITLE
[Bug] Error: certificate has expired

### ISSUE THREAD

**Issue by roniemartinez** [codecov/codecov-action#788]
### Error

```
Run codecov/codecov-action@v2.1.0
  with:
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.7.13/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.7.13/x64/lib
==> linux OS detected
Error: certificate has expired
    at TLSSocket.onConnectSecure (_tls_wrap.js:150[2](https://github.com/roniemartinez/dude/runs/7417077505?check_suite_focus=true#step:12:2):[3](https://github.com/roniemartinez/dude/runs/7417077505?check_suite_focus=true#step:12:3)[4](https://github.com/roniemartinez/dude/runs/7417077505?check_suite_focus=true#step:12:4))
    at TLSSocket.emit (events.js:314:20)
    at TLSSocket._finishInit (_tls_wrap.js:93[7](https://github.com/roniemartinez/dude/runs/7417077505?check_suite_focus=true#step:12:8):[8](https://github.com/roniemartinez/dude/runs/7417077505?check_suite_focus=true#step:12:9))
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:7[11](https://github.com/roniemartinez/dude/runs/7417077505?check_suite_focus=true#step:12:12):12)
```

### Actions
https://github.com/roniemartinez/browsers/runs/7417078453?check_suite_focus=true
https://github.com/roniemartinez/dude/runs/7417077505?check_suite_focus=true

**Comment by danielmklein** [comment]
FWIW -- this also suggests to me that the default of `false` for `fail_ci_if_error` might not work entirely as expected, because ours and others' workflows _are_ failing on these errors.

**Comment by Ronan-ACN** [comment]
FYI, we saw the exact same issue and an update to `codecov/codecov-action@v3` fixed it

**Comment by disconnect3d** [comment]
My projects are also impacted by it. What's the difference between v2 and v3?

**Comment by friedkeenan** [comment]
I had this error when using v3. Reran my CI and now it's fixed again, so the issue seems to have just passed.

**Comment by friedkeenan** [comment]
I am now getting the error again.

**Comment by mafredri** [comment]
We're using `codecov/codecov-action@v3` and seeing this as well. We also explicitly set `fail_ci_if_error: false`.

**Comment by scouten-adobe** [comment]
It was working for a while after yesterday's outage, but appears to be broken again circa 1100 Pacific / 1800 UTC.

**Comment by algomaster99** [comment]
We use `v3.1.0`. Happening with us as well - https://github.com/SpoonLabs/sorald/runs/7435308576?check_suite_focus=true#step:14:9.

**Comment by ryanhill1** [comment]
Same issue as well for v3
![codecov_err](https://user-images.githubusercontent.com/46977852/180054835-a4d7b257-35ca-4b1c-bf02-953424a190c1.png)

**Comment by friedkeenan** [comment]
Issue seems to have resolved for me.

**Comment by soosub** [comment]
> Issue seems to have resolved for me.

Same, thanks a lot!

**Comment by scouten-adobe** [comment]
Wow, this is really wobbly. Just failed for us again (1430 Pacific / 2130 UTC).

https://github.com/contentauth/c2pa-rs/runs/7435111656?check_suite_focus=true

**Comment by guizmaii** [comment]
Doesn't seems to be fixed for us 🤔
