### ISSUE TITLE
Fails to upload after lots of retries

### ISSUE THREAD

**Issue by postlund** [codecov/codecov-action#81]
I've had a lot of problems with timeouts in the past, like the ones mentioned in #37, but since the past couple of days codecov tries ("Sleeping for 30 seconds and trying again") to upload the report but always fails. Unfortunately it's hard to copy the logs from GitHub actions in safari on iOS, but one complete log is here:

https://github.com/postlund/pyatv/runs/743672533?check_suite_focus=true

I'm not really sure what is wrong? Usually I can re-trigger the job and it will work, but now it fails every time. So I can basically not merge PRs. Anyone else seen this lately?

**Comment by k-yomo** [comment]
I'm in  the same situation. The failed action's link is attached below.

https://github.com/k-yomo/lets-meal/runs/744650611?check_suite_focus=true

**Comment by Abhi347** [comment]
Facing the same situation here. More details - https://github.com/Abhi347/codekata/pull/9/checks?check_run_id=757034238

**Comment by thomasrockhu** [comment]
The spike in recent upload failures can be attributed to the recent issue we were having. Please let me know if you are still experiencing the same.

**Comment by postlund** [comment]
I just created PR to re-enable codecov and it failed hard with the exact same error as before. So at least I would say that it's not solved.

https://github.com/postlund/pyatv/runs/766837371?check_suite_focus=true

**Comment by postlund** [comment]
With the latest updates to codecov, it seems to work better. But for some reason the macOS jobs seems to fail (same reason), so it's still not usable.

**Comment by scouten** [comment]
I'm still encountering something very similar, as per this example, which never showed CodeCov status despite several "re-run" attempts: https://github.com/rust-git/rsgit/runs/837276497

Interestingly, I pushed an empty commit to that PR (https://github.com/rust-git/rsgit/pull/50/commits/bc884b7b3d1f5c58cbd3f019e3da6bac8d87d10e) and it worked promptly the first time.

**Comment by scouten** [comment]
On [another thread](https://community.codecov.io/t/codecov-status-stuck-at-waiting-for-status-to-be-reported-on-github/341/40) which is now closed, I found advice to move to checkout V1 action. I [tried that](https://github.com/rust-git/rsgit/pull/38) and it seems to help, but the problem still occurs.

**Comment by thomasrockhu** [comment]
@scouten can you try upgrading to `1.0.10`?

**Comment by MartinNowak** [comment]
It seems that requestretry in [`v1.0.10`](https://github.com/codecov/codecov-action/releases/tag/v1.0.10) keeps retrying infinitely or might get stuck somehow. At least it didn't fail for 5+ minutes in a PR just about now.
Pragmatic workaround:
- downgrade to [`v1.0.7`](https://github.com/codecov/codecov-action/releases/tag/v1.0.7) (before the problematic retry stuff)
- disable [`fail_ci_if_error`](https://github.com/codecov/codecov-action#arguments)

**Comment by marbar3778** [comment]
> It seems that requestretry in [`v1.0.10`](https://github.com/codecov/codecov-action/releases/tag/v1.0.10) keeps retrying infinitely or might get stuck somehow. At least it didn't fail for 5+ minutes in a PR just about now.

I have the same error we split our tests to multiple machines, then run and upload separately. We are getting failures 1 out of 3 runs. This is getting quite annoying

**Comment by thomasrockhu** [comment]
Hi @MartinNowak and @marbar3778, would you be able to provide build urls that we can take a look at? I would really like to get to the bottom of this and get more reliability here.

**Comment by marbar3778** [comment]
v1.0.10: 
- https://github.com/cosmos/cosmos-sdk/runs/849134945?check_suite_focus=true

v1:
- https://github.com/cosmos/cosmos-sdk/runs/848115242?check_suite_focus=true
- https://github.com/cosmos/cosmos-sdk/runs/846591913?check_suite_focus=true
- https://github.com/cosmos/cosmos-sdk/runs/846534886?check_suite_focus=true
- https://github.com/tendermint/tendermint/pull/5078/checks?check_run_id=849505955

we just allowed ci to pass on the failure of upload but were against this. I'm not sure if github saves logs from old runs after we have rerun them. I can dig through more PRs and see later on.

**Comment by thomasrockhu** [comment]
@marbar3778, yes this is clearly not ideal. I've escalated to the product team to see what we can do here.

**Comment by MartinNowak** [comment]
A better workaround for us atm. was to use the bash script directly. Might be a saner choice for simple use-cases in general.

```yaml
env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
run: |
  wget --quiet https://codecov.io/bash -O codecov.sh
  bash codecov.sh -- -f coverage.xml
```

**Comment by scouten** [comment]
> @scouten can you try upgrading to `1.0.10`?

Yes, just merged that into my project.

Encouraging: [That PR](https://github.com/rust-git/rsgit/pull/53) verified _very_ quickly.

**Comment by scouten** [comment]
@thomasrockhu shoot, I spoke too soon. I've seen another stall. Left this one overnight and it still didn't resolve:

https://github.com/rust-git/rsgit/pull/58/checks?check_run_id=884258633

**Comment by paul-pop** [comment]
Another solution we could be looking at is to add another argument like `timeout` to the list of inputs.

Something like that used together with `fail_ci_if_error: false` could be quite nice.

<details><summary>YML example/summary>
```yml
- uses: codecov/codecov-action@v1
   with:
     timeout: 1m
     fail_ci_if_error: false
     ...
```
</details>

**Comment by LasseRafn** [comment]
Status? 😅  its been going on for months now, at times causing our builds to run for an hour rather than 5 min..

**Comment by thomasrockhu** [comment]
Hi all, thanks are working on a few fixes to make uploading more consistent. I'll update here as we make changes.

**Comment by thomasrockhu** [comment]
Hi we've released `1.0.13` which should help with the retries and long uploads. Would you mind trying that and see how it goes?

**Comment by postlund** [comment]
I will make sure to upgrade. However, I do believe it has become much more stable since .12. Can't remember that I have seen any problems lately.

**Comment by scouten** [comment]
Sorry for slow follow-up, but I am now on 1.0.13 and it seems to be working well.

https://github.com/rust-git/rsgit/pull/78
