### ISSUE TITLE
Not able to see code coverage as Checks on PR level

### ISSUE THREAD

**Issue by fahadshehzada** [codecov/codecov-action#83]
Run codecov/codecov-action@v1.0.7
  with:
    token: ***
    file: services/billing/src/coverage/clover.xml
    flags: billing
/bin/bash codecov.sh -f services/billing/src/coverage/clover.xml -n -F billing

![Capturecodecov2](https://user-images.githubusercontent.com/61680750/84687676-8bc23e80-af57-11ea-8803-8e737bb3984b.PNG)

Running above GitHub action, generating report as well but not showing on checks with code coverage stats. I need code coverage as checks on PR level

![Capturecodecov](https://user-images.githubusercontent.com/61680750/84687586-6c2b1600-af57-11ea-9aa3-4b962b0b5d22.PNG)

**Comment by thomasrockhu** [comment]
Closing as a dupe https://github.com/codecov/codecov-python/issues/281
