### ISSUE TITLE
Codecov comments not popping up on pull requests?

### ISSUE THREAD

**Issue by ffMathy** [codecov/codecov-action#84]
In my repository https://github.com/dogger/dogger.io, comments don't pop up when I am making a new pull request. How do I enable this, with the GitHub action?

What am I doing wrong here?

**Comment by fernando-mc** [comment]
Seeing the same thing here - https://github.com/fernando-mc/serverless-surveys

Happy to provide any context that might help debug this.

**Comment by gcgbarbosa** [comment]
Same here. Codecov.io has an alert complaining that the status of the CI is pending, but looking at the Github action that runs the CI I can tell that the status is there.

**Comment by robinbiondi** [comment]
Same for me

**Comment by markov00** [comment]
I've also noticed that today when for the first time I've added the codecov reporting via github action.
It was working fine when running codecov from a Jenkins CI job

**Comment by sfdye** [comment]
If you have `codecov.yml`:
```
comment:
  after_n_builds: 3 
```

you probably need to update `after_n_builds` to be the number of reports uploaded by Github Action.

**Comment by thomasrockhu** [comment]
Closing this out, but if this is still an issue, please open a ticket in our [community boards](https://community.codecov.io)
