### ISSUE TITLE
Bump Node 12

### ISSUE THREAD

**Issue by casperdcl** [codecov/codecov-action#871]
The action produces the following warning:

> **Warning**
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: codecov/codecov-action@v1

**Comment by hhirtz** [comment]
You are using the v1. This has been fixed in v3. See #689

```diff
- uses: codecov/codecov-action@v1
+ uses: codecov/codecov-action@v3
```
