### ISSUE TITLE
How to use codecov-action for Java Project?

### ISSUE THREAD

**Issue by harkue** [codecov/codecov-action#91]
I see an example for python in README.md. How to use codecov-action for Java Project?

**Comment by merkrafter** [comment]
It depends on your build/test system. Basically, all you need to know is where your report (xml file) is located at. Here is an [example](https://github.com/merkrafter/Merkompiler/blob/feature/coverage-reports/.github/workflows/quality_assurance.yml) using maven and JaCoCo.

**Comment by CXwudi** [comment]
> It depends on your build/test system. Basically, all you need to know is where your report (xml file) is located at. Here is an [example](https://github.com/merkrafter/Merkompiler/blob/feature/coverage-reports/.github/workflows/quality_assurance.yml) using maven and JaCoCo.

The example is not available anymore

**Comment by merkrafter** [comment]
Ah, sorry. It's fixed now.
