### ISSUE TITLE
Failing action and stuck on depending checks

### ISSUE THREAD

**Issue by ilyachch** [codecov/codecov-action#98]
```
Run codecov/codecov-action@v1
  with:
    token: ***
    file: ./coverage.xml
    flags: pull_requests
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.6.11/x64
##[warning]Codecov warning: connect ETIMEDOUT 35.199.43.247:443
bash codecov.sh -f ./coverage.xml -n  -F pull_requests
codecov.sh: line 1: undefined: command not found
##[warning]Codecov warning: The process 'bash' failed with exit code 127
```

Also, I'm using checkout v1 and tried different versions of codecov action

https://github.com/ilyachch/django-partisan/runs/887400923

![image](https://user-images.githubusercontent.com/1570221/88031873-e0a03880-cb45-11ea-8c25-9d06f1cca4c6.png)

**Comment by ilyachch** [comment]
and if we will go to https://35.199.43.247/ we got not secure connection and 404 response

**Comment by thomasrockhu** [comment]
@ilyachch I noticed `v1` was pointing to an older version of the action. I've updated it, would you let me know if this is still a problem?

**Comment by ilyachch** [comment]
@thomasrockhu yes, now it works, thanks!
