### ISSUE TITLE
Codecov action does not pick up the configuration YAML file

### ISSUE THREAD

**Issue by ASHIQUEMD** [codecov/codecov-action#991]
We have integrated Codecov in our [github actions](https://github.com/Azure/azure-functions-dapr-extension/blob/d66acdafb4972b413a5b1b5352479d150f2cfe6a/.github/workflows/build.yml#L42-L47). Here is the [codecov.yml ](https://github.com/Azure/azure-functions-dapr-extension/blob/master/.github/codecov.yml)file.

But codecov.yml file hasn't synced with codecov settings as shown below, because of that condition written in codecov.yml isn't getting executed.

<img width="1223" alt="image" src="https://github.com/codecov/codecov-action/assets/16832724/75429031-afde-4fe5-966c-c9b13d337d93">

**Comment by shubham1172** [comment]
Hi @thomasrockhu-codecov, could you help here?

**Comment by huxuan** [comment]
Just want to confirm what we need is the `CI-level YAML` mentioned here [1] rather than `Repository YAML`.

[1] https://docs.codecov.com/docs/codecov-yaml

**Comment by ASHIQUEMD** [comment]
@huxuan we have codecov.yml defined in [our Repository under .github folder](https://github.com/Azure/azure-functions-dapr-extension/blob/master/.github/codecov.yml). So we need `Repository YAML` file to sync with codecov setting.

**Comment by shubham1172** [comment]
Hi @thomasrockhu-codecov, yes I had installed it.

Here is a screenshot:
<img width="621" alt="image" src="https://github.com/codecov/codecov-action/assets/22132944/1c81eac6-9500-4812-97e6-8651efb19b57">

Anyway for now we are using CI-level YAML. We started pushing the codecov.yaml via codecov GitHub actions and it works for us. Here is the PR: https://github.com/Azure/azure-functions-dapr-extension/pull/122

Checks started showing up with this change.
<img width="802" alt="image" src="https://github.com/codecov/codecov-action/assets/22132944/4bd4b33c-d530-4214-bcd5-421bbba9e547">

**Comment by huxuan** [comment]
Thanks @shubham1172 for the sample MR, I did not make it because I forget the specify the `codecov.yml` in `file` config.

@ASHIQUEMD Is it possible to have the GitHub action find the CI-level YAML file automatically? I suppose it could be the `codecov.yml` in the root directory or `.github` directory. What do you think of?

**Comment by ASHIQUEMD** [comment]
@huxuan I am not from Codecov team, so I can't say if this can be done or not. I was integrating Codecov in our project and faced the issue. 

But I agree with your point, it would be great if GitHub action can find the CI-level YAML file automatically.
